packages:
  - 'frontend/*'
overrides:
  vite-plugin-monaco-editor: 'npm:vite-plugin-monaco-editor-new@1.1.3'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - meta-json-schema
  - oxc-resolver
allowBuilds:
  '@parcel/watcher': false
  core-js: true
  meta-json-schema: true
supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
    - current
  cpu:
    - x64
    - arm64
    - current
  libc:
    - glibc
    - musl
    - current
