/* oxlint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'
import * as __TAURI_EVENT from '@tauri-apps/api/event'

/** Commands */
export const commands = {
  callRpc: (method: string, params: RpcValue) =>
    typedError<RpcValue, RpcError>(
      __TAURI_INVOKE('call_rpc', { method, params }),
    ),
}

/** Events */
export const events = {
  appUpdateStateChanged: makeEvent<AppUpdateStateChanged>(
    'app-update-state-changed',
  ),
  clashWsEvent: makeEvent<ClashWsEvent>('clash-ws-event'),
  configurationStatusChanged: makeEvent<ConfigurationStatusChanged>(
    'configuration-status-changed',
  ),
  coreLogsChanged: makeEvent<CoreLogsChanged>('core-logs-changed'),
  coreStatusChangedEvent: makeEvent<CoreStatusChangedEvent>(
    'core-status-changed-event',
  ),
  schemeRequestReceivedEvent: makeEvent<SchemeRequestReceivedEvent>(
    'scheme-request-received-event',
  ),
  serviceStatusChangedEvent: makeEvent<ServiceStatusChangedEvent_Deserialize>(
    'service-status-changed-event',
  ),
  storageValueChangedEvent: makeEvent<StorageValueChangedEvent>(
    'storage-value-changed-event',
  ),
  windowMessageEvent: makeEvent<WindowMessageEvent>('window-message-event'),
  windowReadyEvent: makeEvent<WindowReadyEvent>('window-ready-event'),
}

/* Types */
export type AppUpdatePhase =
  | 'idle'
  | 'checking'
  | 'up_to_date'
  | 'available'
  | 'downloading'
  | 'cancelling'
  | 'cancelled'
  | 'verifying'
  | 'ready'
  | 'installing'
  | 'failed'

export type AppUpdateRelease = {
  version: string
  date: string | null
  body: string | null
}

export type AppUpdateSnapshot = {
  revision: number
  phase: AppUpdatePhase
  release: AppUpdateRelease | null
  downloaded: number
  total: number | null
  speed: number | null
  source: UpdateSource | null
  error: string | null
  last_checked_at: string | null
  supported: boolean
  endpoints: string[]
}

export type AppUpdateStateChanged = AppUpdateSnapshot

export type ClashConnectionsConnectorState =
  'disconnected' | 'connecting' | 'connected'

/**  Pushed on every connection sample; size is independent of connection count. */
export type ClashConnectionsSummary = {
  downloadTotal: number
  uploadTotal: number
  downloadSpeed: number
  uploadSpeed: number
  memory: number | null
  connectionCount: number
  /**
   *  Keyed by chain member name (group or node); summed over every
   *  connection whose `chains` contains that name.
   */
  memberRates: { [key in string]: TrafficRate }
}

export type ClashCoreType =
  'mihomo' | 'mihomo-alpha' | 'clash-rs' | 'clash-rs-alpha' | 'clash' | 'meow'

export type ClashWsEvent = {
  sequence: number
  update: ClashWsUpdate
}

export type ClashWsKind = 'connections' | 'logs' | 'traffic' | 'memory'

export type ClashWsMemory = {
  inuse: number
  oslimit: number
}

export type ClashWsRecording = {
  connections: boolean
  logs: boolean
  traffic: boolean
  memory: boolean
}

export type ClashWsSnapshot = {
  sequence: number
  state: ClashConnectionsConnectorState
  recording: ClashWsRecording
  connections: ClashConnectionsSummary[]
  traffic: ClashWsTraffic[]
  memory: ClashWsMemory[]
}

export type ClashWsTraffic = {
  up: number
  down: number
}

export type ClashWsUpdate =
  | { kind: 'reset'; data: ClashWsSnapshot }
  | { kind: 'state_changed'; data: ClashConnectionsConnectorState }
  | { kind: 'connections_updated'; data: ClashConnectionsSummary }
  | { kind: 'traffic_updated'; data: ClashWsTraffic }
  | { kind: 'memory_updated'; data: ClashWsMemory }
  | { kind: 'recording_changed'; data: ClashWsRecording }
  | { kind: 'history_cleared'; data: ClashWsKind }

/**
 *  Identity of the config the running core actually adopted.
 *
 *  `source_hash` is computed over the caller's own file and `effective_hash`
 *  over the canonical form the core is running, both FNV-1a over canonical
 *  YAML. A caller that holds the source file can therefore confirm the
 *  service read the same bytes it wrote, without reimplementing the hash.
 *  The manager's private runtime copy path is deliberately not exposed: it
 *  lives in a 0o700 directory the caller cannot read, so it would only
 *  mislead.
 */
export type ConfigRevisionInfo = {
  epoch: number
  generation: number
  source_hash: string
  effective_hash: string
}

export type ConfigurationStatus = {
  event_seq: number
  maintenance: string | null
  source_versions: SourceVersions
  runtime: RuntimeConvergence
  effects: EffectConvergence[]
  /**  The latest background-source receipt per profile. */
  sources: SourceStatus[]
  active: string | null
  recent_operations: OperationStatus[]
}

export type ConfigurationStatusChanged = ConfigurationStatus

export type ConvergenceHealth =
  | 'healthy'
  | 'pending'
  | 'retry_scheduled'
  | 'waiting_dependency'
  | 'blocked'
  | 'recovery_required'

/**
 *  The core's control endpoint, as the manager resolved it.
 *
 *  A deliberately separate type from `clash_api::Host`: clash-api is an
 *  internal dependency of the core manager and must not leak into the wire
 *  dependency tree. The controller secret is never carried here. Clients read
 *  applied credentials through the private `/v2/core/api-connection` endpoint;
 *  the IPC transport's authorization gate is the socket ACL.
 */
export type CoreControllerInfo =
  | ({ NamedPipe: string } & { Http?: never; UnixSocket?: never })
  | ({ UnixSocket: string } & { Http?: never; NamedPipe?: never })
  /**  Normalized base URL with any credentials removed. */
  | ({ Http: string } & { NamedPipe?: never; UnixSocket?: never })

/**
 *  The manager's health observation for the active core. Absent while the
 *  core is stopping or stopped.
 */
export type CoreHealthInfo = {
  state: CoreHealthState
  /**  Unix milliseconds of the last health-state transition. */
  changed_at: number
  consecutive_failures: number
  /**  Last probe failure detail, capped by the manager at 512 bytes. */
  last_error: string | null
  /**  Unix milliseconds of the last successful probe. */
  last_success_at: number | null
}

/**  Health observation state for the active core. */
export type CoreHealthState = 'Starting' | 'Healthy' | 'Unhealthy'

export type CoreInfos = CoreInfos_Serialize | CoreInfos_Deserialize

export type CoreInfos_Deserialize = {
  instance_id?: string | null
  type: CoreType | null
  state: CoreState
  state_changed_at: number
  config_path: string | null
  /**
   *  Omitted rather than null when absent, so a payload carrying none of
   *  the fields below is byte-identical to the pre-S7 wire format.
   */
  controller?: CoreControllerInfo | null
  health?: CoreHealthInfo | null
  revision?: ConfigRevisionInfo | null
  detail?: CoreStateDetail | null
}

export type CoreInfos_Serialize = {
  instance_id?: string | null
  type: CoreType | null
  state: CoreState
  state_changed_at: number
  config_path: string | null
  /**
   *  Omitted rather than null when absent, so a payload carrying none of
   *  the fields below is byte-identical to the pre-S7 wire format.
   */
  controller?: CoreControllerInfo | null
  health?: CoreHealthInfo | null
  revision?: ConfigRevisionInfo | null
  detail?: CoreStateDetail | null
}

export type CoreLogCursor = {
  generation: string
  sequence: number
}

export type CoreLogStatus = {
  generation: string
  version: number
  first: CoreLogCursor | null
  head: CoreLogCursor | null
  bytes: number
  error: string | null
  discarded: number
}

export type CoreLogsChanged = {
  status: CoreLogStatus
}

export type CoreState = 'Running' | { Stopped: string | null }

/**
 *  The core's full lifecycle state.
 *
 *  [`CoreState`] is a two-valued projection kept for wire compatibility: it
 *  reports `Starting` and `Restarting` as `Stopped(None)`, so a crash loop is
 *  indistinguishable from a real stop. This is the faithful view; prefer it
 *  when present.
 */
export type CoreStateDetail =
  | ({
      Stopped: {
        reason: string | null
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Starting: {
        epoch: number
      }
    } & {
      Restarting?: never
      Running?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Running: {
        epoch: number
        pid: number
      }
    } & {
      Restarting?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Restarting: {
        epoch: number
        attempt: number
      }
    } & {
      Running?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Switching: {
        from: number | null
        to: number
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
    })
  | ({
      Stopping: {
        epoch: number
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopped?: never
      Switching?: never
    })

export type CoreStatusChangedEvent = CoreStatusInfo

export type CoreStatusInfo = {
  controller: CoreControllerInfo | null
  host: ExecutionHost
  connectivity: EndpointConnectivity
  generation: number
  state: CoreStateDetail | null
  state_changed_at: number
  revision: RevisionIdInfo | null
  healthy: boolean | null
}

export type CoreType = { clash: ClashCoreType } | 'singbox'

export type EffectConvergence = {
  kind: EffectKind
  health: ConvergenceHealth
  desired_revision: number
  applied_revision: number
  attempts: number
  automatic_remaining: number
  /**  What kind of failure the effect is in, for the UI to localize. */
  code: EffectFailureCode | null
  /**  The failure's diagnostic text, as the owner reported it. */
  message: string | null
}

/**
 *  Why an effect is not in its desired state, in the terms the UI localizes.
 *
 *  One value per kind of failure, named after the effect that failed. The
 *  owner that classifies a failure is the one that picks the code; the
 *  message beside it is only the diagnostic text.
 */
export type EffectFailureCode =
  | 'hotkey_invalid_bindings'
  | 'hotkey_partial_registration'
  | 'hotkey_shut_down'
  | 'hotkey_stopped'
  | 'logger_refresh_failed'
  | 'widget_unavailable'
  | 'widget_apply_failed'
  | 'tray_refresh_failed'
  | 'effect_owner_silent'
  | 'proxy_guard_waiting_dependency'
  | 'auto_launch_failed'
  | 'pac_disable_failed'
  | 'pac_apply_failed'
  | 'pac_unsupported'
  | 'system_proxy_apply_failed'
  | 'system_proxy_port_unresolved'
  | 'system_proxy_restore_failed'
  | 'system_proxy_shut_down'
  | 'system_proxy_stopped'

/**
 *  Execution order of a plan. The ordering is load-bearing: the tray menu is
 *  rendered with the process-wide locale, and the proxy guard re-applies the
 *  system proxy value that the `SystemProxy` effect just installed.
 */
export type EffectKind =
  | 'locale'
  | 'logger'
  | 'auto_launch'
  | 'system_proxy'
  | 'proxy_guard'
  | 'hotkeys'
  | 'widget'
  | 'tray'

export type EndpointConnectivity =
  | { kind: 'connected' }
  | { kind: 'shut_down' }
  | { kind: 'handing_off'; from: ExecutionHost; to: ExecutionHost }
  /**
   *  The endpoint is unreachable. `desired` names the committed host; the
   *  router never falls back on its own.
   */
  | { kind: 'degraded'; desired: ExecutionHost; reason: string }

/**
 *  Which controller owns the runtime. The app perceives the difference in
 *  exactly two places: this tag on the endpoint slot, and the handoff
 *  protocol.
 */
export type ExecutionHost = 'local' | 'service'

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream. The service's own files are queried through the bounded
 *  `/v1/logs/*` session RPCs when `log_query_version` is present; directory
 *  permissions remain unchanged and these logs never enter the event stream.
 */
export type LogPathsInfo = LogPathsInfo_Serialize | LogPathsInfo_Deserialize

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream. The service's own files are queried through the bounded
 *  `/v1/logs/*` session RPCs when `log_query_version` is present; directory
 *  permissions remain unchanged and these logs never enter the event stream.
 */
export type LogPathsInfo_Deserialize = {
  /**
   *  The service's own logs: JSON lines from `tracing-appender`, rotated
   *  daily, seven files kept.
   */
  service_dir: string
  /**
   *  The core log archive: one rolling JSONL stream, rotated by size and
   *  retained by count. Absent when the manager's sink is switched off, in
   *  which case no such directory exists at all.
   */
  core_dir?: string | null
}

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream. The service's own files are queried through the bounded
 *  `/v1/logs/*` session RPCs when `log_query_version` is present; directory
 *  permissions remain unchanged and these logs never enter the event stream.
 */
export type LogPathsInfo_Serialize = {
  /**
   *  The service's own logs: JSON lines from `tracing-appender`, rotated
   *  daily, seven files kept.
   */
  service_dir: string
  /**
   *  The core log archive: one rolling JSONL stream, rotated by size and
   *  retained by count. Absent when the manager's sink is switched off, in
   *  which case no such directory exists at all.
   */
  core_dir?: string | null
}

export type OperationStatus = {
  operation_id: string
  domain: string
  outcome: string
  conclusion: string
  message: string | null
}

/**  Stable profile identifier. It is also the key used by [`Profiles::items`]. */
export type ProfileId = string

/**
 *  The compare-and-swap identity of a config revision.
 *
 *  Deliberately a subset of [`ConfigRevisionInfo`]: the manager's CAS compares
 *  epoch, generation and `effective_hash` only, so carrying `source_hash` here
 *  would imply it takes part.
 */
export type RevisionIdInfo = {
  epoch: number
  generation: number
  effective_hash: string
}

export type RpcError = {
  kind: string
  message: string
  code: string | null
  retryable: boolean | null
  operation_id: string | null
  domain_error: RpcValue | null
}

/**
 *  Specta 0.0.12 cannot recursively export `serde_json::Value` directly.
 *  Keep the JSON wire transparent while exporting it as TypeScript `any`.
 */
export type RpcValue = any

export type RuntimeConvergence = {
  health: ConvergenceHealth
  operation_id: string | null
  attempts: number
  automatic_remaining: number
  message: string | null
}

export type RuntimeInfos = {
  service_data_dir: string
  service_config_dir: string
  nyanpasu_config_dir: string
  nyanpasu_data_dir: string
}

/**
 *  Emitted to the frontend after a `clash-nyanpasu`/`clash` custom-scheme deep
 *  link joins [`PendingDeepLinks`]. It carries no URL: it only asks a listening
 *  frontend to take the queue through [`take_pending_deep_links`].
 *
 *  Event name: `scheme-request-received-event` (derived by `tauri_specta`).
 */
export type SchemeRequestReceivedEvent = null

export type ServiceCompat =
  /**  daemon 未安装 / 未运行 / 未上报 server 信息，没有可判定的版本。 */
  | { kind: 'unknown' }
  /**  主版本匹配，允许进入 Service backend。 */
  | { kind: 'compatible'; server_version: string }
  /**
   *  主版本不匹配（典型：v1.4.5），或主版本对但低于最低版本（典型：
   *  v2.0.0-rc.1）。fail-closed。
   */
  | {
      kind: 'incompatible'
      server_version: string
      required_major: number
      /**
       *  供 UI 展示：只说"需要 v2.x"无法解释一台 major 正确却被拒的
       *  daemon，它装的**就是** v2.x。
       */
      required_min: string
    }
  /**  server 上报的版本不是合法 semver。fail-closed。 */
  | { kind: 'unparsable'; server_version: string }

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus =
  ServiceHostStatus_Serialize | ServiceHostStatus_Deserialize

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus_Deserialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Deserialize | null
  phase: ServicePhase
  compat: ServiceCompat
  restart_attempts: number
}

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus_Serialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Serialize | null
  phase: ServicePhase
  compat: ServiceCompat
  restart_attempts: number
}

export type ServicePhase =
  | 'probing'
  | 'not_installed'
  | 'daemon_stopped'
  | 'installing'
  | 'starting_daemon'
  | 'ready'
  /**  Version gate failed closed: upgrade required, never downgraded to. */
  | 'incompatible'
  | 'restarting'
  /**  Auto-restart budget spent; waits for `EnsureReady` or a successful explicit start. */
  | 'exhausted'
  | 'uninstalling'
  /**
   *  The probe itself failed or timed out (F5): what the daemon actually
   *  is cannot be determined. Never treated as `DaemonStopped` -- an
   *  unreachable daemon might still be holding a core open, so callers
   *  that gate on "no core held" (the uninstall guard, `RecoverEndpoint`'s
   *  restart) must refuse rather than proceed.
   */
  | 'unknown'

export type ServiceStatus = 'not_installed' | 'stopped' | 'running'

export type ServiceStatusChangedEvent =
  ServiceStatusChangedEvent_Serialize | ServiceStatusChangedEvent_Deserialize

export type ServiceStatusChangedEvent_Deserialize =
  ServiceHostStatus_Deserialize

export type ServiceStatusChangedEvent_Serialize = ServiceHostStatus_Serialize

export type SourceOrigin =
  'scheduled_refresh' | 'manual_refresh' | 'external_file'

export type SourceOutcome =
  | { kind: 'committed'; operation_id: string | null }
  /**  Its result no longer applied to the profile and was dropped (V31). */
  | { kind: 'superseded'; reason: string }
  | { kind: 'failed'; message: string }
  /**
   *  The content reached the source transaction and was refused; nothing
   *  was committed and an external file is never rewritten (V33).
   */
  | { kind: 'rejected'; code: string; message: string }

export type SourceStatus = {
  profile: ProfileId
  name: string
  origin: SourceOrigin
  outcome: SourceOutcome
  health: ConvergenceHealth
  /**  Unix milliseconds. */
  at: number
}

export type SourceVersions = {
  application: number
  clash: number
  session: number
  profiles: number
}

export type StatusResBody = StatusResBody_Serialize | StatusResBody_Deserialize

export type StatusResBody_Deserialize = {
  version: string
  core_infos: CoreInfos_Deserialize
  runtime_infos: RuntimeInfos
  /**
   *  Declared last and omitted rather than null when absent, so a payload
   *  without it is byte-identical to the pre-L3 format — the rule S7 used for
   *  `CoreInfos`. The service always sends it; the `Option` exists so every
   *  existing golden literal stays unchanged.
   */
  logs?: LogPathsInfo_Deserialize | null
  /**  Optional viewer protocol; absence does not affect core control compatibility. */
  log_query_version?: number | null
}

export type StatusResBody_Serialize = {
  version: string
  core_infos: CoreInfos_Serialize
  runtime_infos: RuntimeInfos
  /**
   *  Declared last and omitted rather than null when absent, so a payload
   *  without it is byte-identical to the pre-L3 format — the rule S7 used for
   *  `CoreInfos`. The service always sends it; the `Option` exists so every
   *  existing golden literal stays unchanged.
   */
  logs?: LogPathsInfo_Serialize | null
  /**  Optional viewer protocol; absence does not affect core control compatibility. */
  log_query_version?: number | null
}

/**
 *  Event emitted to all windows when a storage value changes.
 *  Event name: `storage-value-changed-event`
 */
export type StorageValueChangedEvent = {
  key: string
  /**  The new JSON-encoded value, or `None` if the key was removed. */
  value: string | null
}

export type TrafficRate = {
  download: number
  upload: number
}

export type UpdateSource = 'nyanpasu' | 'github' | 'ghfast'

/**  Message for inter-window communication */
export type WindowMessageEvent = {
  /**  Source window label */
  from: string
  /**  Target window label (use "*" for broadcast) */
  to: string
  /**  Message type/event name */
  event: string
  /**  Message payload */
  payload: any
}

/**
 *  Event emitted by the frontend when a window's webview is ready and visible.
 *  Carries the window label so the backend can handle per-window logic.
 *  Event name: `window-ready-event`
 */
export type WindowReadyEvent = {
  label: string
}

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}

type EventEmit<T> = [T] extends [null]
  ? () => Promise<void>
  : (payload: T) => Promise<void>

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent =
    (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
      cb({
        ...event,
        payload: deserialize ? deserialize(event.payload) : event.payload,
      })
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload)

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  }

  const fn = (
    target:
      | import('@tauri-apps/api/webview').Webview
      | import('@tauri-apps/api/window').Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  })

  return Object.assign(fn, base)
}
