use super::{Ctx, MigrationState, MigrationStep, ModuleMigrator};
use anyhow::{Context, bail};
use chrono::{SecondsFormat, Utc};
use semver::Version;
use serde::{Deserialize, Serialize};
use std::{
    collections::BTreeMap,
    fs::OpenOptions,
    io::{self, Write},
    path::Path,
};

pub const STORE_SCHEMA_VERSION: u64 = 2;
pub const STORE_FILE_NAME: &str = "migration-state.yaml";
const STORE_TMP_FILE_NAME: &str = "migration-state.yaml.tmp";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct AppMigrationState {
    pub last_succeeded: Option<Version>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct ModuleState {
    pub applied_revision: u64,
    pub baseline_revision: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TaskRecord {
    pub module: String,
    pub revision: u64,
    pub introduced_in: Version,
    pub state: MigrationState,
    pub started_at: Option<String>,
    pub finished_at: Option<String>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MigrationStore {
    pub store_schema_version: u64,
    #[serde(default)]
    pub app: AppMigrationState,
    #[serde(default)]
    pub modules: BTreeMap<String, ModuleState>,
    #[serde(default)]
    pub tasks: BTreeMap<String, TaskRecord>,
}

impl Default for MigrationStore {
    fn default() -> Self {
        Self {
            store_schema_version: STORE_SCHEMA_VERSION,
            app: AppMigrationState::default(),
            modules: BTreeMap::new(),
            tasks: BTreeMap::new(),
        }
    }
}

impl MigrationStore {
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }

        let raw = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read migration state {}", path.display()))?;
        let store: Self = serde_yaml::from_str(&raw)
            .with_context(|| format!("failed to parse migration state {}", path.display()))?;
        if store.store_schema_version != STORE_SCHEMA_VERSION {
            bail!(
                "unsupported migration store schema version {}",
                store.store_schema_version
            );
        }
        Ok(store)
    }

    pub fn flush_atomic(&self, path: &Path) -> anyhow::Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).with_context(|| {
                format!("failed to create migration state dir {}", parent.display())
            })?;
        }

        let content = serde_yaml::to_string(self).context("failed to serialize migration state")?;
        let tmp_path = path.with_file_name(STORE_TMP_FILE_NAME);
        {
            let mut file = OpenOptions::new()
                .create(true)
                .write(true)
                .truncate(true)
                .open(&tmp_path)
                .with_context(|| {
                    format!(
                        "failed to open temporary migration state {}",
                        tmp_path.display()
                    )
                })?;
            file.write_all(
                "# This file is generated by the migration system, do not edit it manually.\n"
                    .as_bytes(),
            )
            .context("failed to write migration state header")?;
            file.write_all(content.as_bytes())
                .context("failed to write migration state")?;
            file.sync_all()
                .context("failed to sync temporary migration state")?;
        }

        replace_file(&tmp_path, path).with_context(|| {
            format!(
                "failed to replace migration state {} with {}",
                path.display(),
                tmp_path.display()
            )
        })?;
        Ok(())
    }

    pub fn task_state(&self, id: &str) -> Option<MigrationState> {
        self.tasks.get(id).map(|task| task.state)
    }

    pub fn module_state(&self, module: &str) -> ModuleState {
        self.modules.get(module).copied().unwrap_or_default()
    }

    pub fn ensure_module(
        &mut self,
        module: &dyn ModuleMigrator,
        ctx: &Ctx,
    ) -> anyhow::Result<bool> {
        if self.modules.contains_key(module.module()) {
            return Ok(false);
        }

        let baseline = module.detect_baseline(ctx)?;
        self.modules.insert(
            module.module().to_string(),
            ModuleState {
                applied_revision: baseline,
                baseline_revision: baseline,
            },
        );
        Ok(true)
    }

    pub fn mark_in_progress(&mut self, step: &dyn MigrationStep) {
        let now = timestamp();
        self.tasks.insert(
            step.id().to_string(),
            TaskRecord {
                module: step.module().to_string(),
                revision: step.revision(),
                introduced_in: step.introduced_in().clone(),
                state: MigrationState::InProgress,
                started_at: Some(now),
                finished_at: None,
                error: None,
            },
        );
    }

    pub fn mark_completed(&mut self, step: &dyn MigrationStep) {
        let now = timestamp();
        let task = self
            .tasks
            .entry(step.id().to_string())
            .or_insert_with(|| TaskRecord {
                module: step.module().to_string(),
                revision: step.revision(),
                introduced_in: step.introduced_in().clone(),
                state: MigrationState::NotStarted,
                started_at: Some(now.clone()),
                finished_at: None,
                error: None,
            });

        task.module = step.module().to_string();
        task.revision = step.revision();
        task.introduced_in = step.introduced_in().clone();
        task.state = MigrationState::Completed;
        task.started_at.get_or_insert_with(|| now.clone());
        task.finished_at = Some(now);
        task.error = None;
    }

    pub fn mark_failed(&mut self, step: &dyn MigrationStep, error: &anyhow::Error) {
        let now = timestamp();
        let task = self
            .tasks
            .entry(step.id().to_string())
            .or_insert_with(|| TaskRecord {
                module: step.module().to_string(),
                revision: step.revision(),
                introduced_in: step.introduced_in().clone(),
                state: MigrationState::NotStarted,
                started_at: Some(now.clone()),
                finished_at: None,
                error: None,
            });

        task.module = step.module().to_string();
        task.revision = step.revision();
        task.introduced_in = step.introduced_in().clone();
        task.state = MigrationState::Failed;
        task.started_at.get_or_insert_with(|| now.clone());
        task.finished_at = Some(now);
        task.error = Some(format!("{error:#}"));
    }

    pub fn bump_module(&mut self, module: &str, revision: u64) {
        let state = self.modules.entry(module.to_string()).or_default();
        state.applied_revision = state.applied_revision.max(revision);
    }

    pub fn set_last_succeeded(&mut self, version: Version) {
        self.app.last_succeeded = Some(version);
    }
}

fn timestamp() -> String {
    Utc::now().to_rfc3339_opts(SecondsFormat::Millis, true)
}

#[cfg(not(windows))]
fn replace_file(from: &Path, to: &Path) -> io::Result<()> {
    std::fs::rename(from, to)
}

#[cfg(windows)]
fn replace_file(from: &Path, to: &Path) -> io::Result<()> {
    use std::os::windows::ffi::OsStrExt;

    const MOVEFILE_REPLACE_EXISTING: u32 = 0x1;
    const MOVEFILE_WRITE_THROUGH: u32 = 0x8;

    unsafe extern "system" {
        fn MoveFileExW(
            lp_existing_file_name: *const u16,
            lp_new_file_name: *const u16,
            dw_flags: u32,
        ) -> i32;
    }

    fn wide(path: &Path) -> Vec<u16> {
        path.as_os_str().encode_wide().chain(Some(0)).collect()
    }

    let from = wide(from);
    let to = wide(to);
    let result = unsafe {
        MoveFileExW(
            from.as_ptr(),
            to.as_ptr(),
            MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH,
        )
    };
    if result == 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn atomic_write_replaces_existing_store() {
        let temp = tempfile::tempdir().unwrap();
        let path = temp.path().join(STORE_FILE_NAME);

        let mut store = MigrationStore::default();
        store.set_last_succeeded(Version::parse("2.0.0").unwrap());
        store.flush_atomic(&path).unwrap();

        store.modules.insert(
            "profiles".to_string(),
            ModuleState {
                applied_revision: 2,
                baseline_revision: 0,
            },
        );
        store.flush_atomic(&path).unwrap();

        let loaded = MigrationStore::load(&path).unwrap();
        assert_eq!(
            loaded.modules.get("profiles").copied(),
            Some(ModuleState {
                applied_revision: 2,
                baseline_revision: 0,
            })
        );
        assert!(!temp.path().join(STORE_TMP_FILE_NAME).exists());
    }
}
