use super::{
    super::{SessionPortResolver, runtime},
    ports::RuntimeBuildPort,
};
use crate::enhance::{
    EnhanceScriptRunner, FsProfileContentSource, RuntimeBuildInput, RuntimeBuilder,
    runtime_snapshot_data_from_artifact,
};
use async_trait::async_trait;
use std::{path::PathBuf, sync::Arc};

pub(in crate::client) struct FsRuntimeBuildAdapter {
    pub profiles_dir: PathBuf,
    pub paths: runtime::RuntimePaths,
    pub ports: Arc<SessionPortResolver>,
}

#[async_trait]
impl RuntimeBuildPort for FsRuntimeBuildAdapter {
    fn core_spec(
        &self,
        core: &nyanpasu_config::application::ClashCore,
    ) -> anyhow::Result<nyanpasu_core_manager::CoreSpec> {
        super::super::runtime_core_spec(core)
    }

    async fn build(
        &self,
        revision: runtime::RuntimeRevision,
        profiles: Arc<nyanpasu_config::profile::Profiles>,
        clash: nyanpasu_config::clash::config::ClashConfig,
        app: nyanpasu_config::application::NyanpasuAppConfig,
    ) -> anyhow::Result<Arc<runtime::RuntimeSnapshot>> {
        let resolved_ports = self.ports.resolve(&clash)?;
        let profiles_dir = self.profiles_dir.clone();
        tokio::task::spawn_blocking(move || {
            let core = app.core;
            let builtin_enabled = app.enable_builtin_enhanced;
            let content = FsProfileContentSource::new(profiles_dir);
            let scripts = EnhanceScriptRunner::new()?;
            let input = RuntimeBuildInput {
                profiles: profiles.clone(),
                clash,
                app,
                resolved_ports,
            };
            let artifact = RuntimeBuilder::build(&input, &content, &scripts)?;
            let data =
                runtime_snapshot_data_from_artifact(artifact, &profiles, core, builtin_enabled)?;
            let yaml = format!(
                "# Generated by Clash Nyanpasu\n\n{}",
                serde_yaml::to_string(&data.config)?
            );
            Ok(Arc::new(runtime::RuntimeSnapshot::from_data(
                revision,
                core,
                Arc::from(yaml.into_bytes()),
                data,
            )))
        })
        .await?
    }

    async fn publish(&self, snapshot: &runtime::RuntimeSnapshot) -> anyhow::Result<()> {
        runtime::write_product(self.paths.product().as_std_path(), snapshot.product_bytes()).await
    }
}
