[package]
name = 'nyanpasu-application'
version = '0.1.0'
repository.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = 'nyanpasu_application'

[dependencies]
camino = '1'
nyanpasu-core-manager = { workspace = true }
nyanpasu-ipc = { workspace = true }
nyanpasu-utils = { workspace = true }
clash-api = { workspace = true }
async-trait = '0.1'
futures = '0.3'
futures-util = '0.3'
indexmap = { version = '2', features = ['serde'] }
uuid = { version = '1', features = ['v4', 'serde'] }
thiserror = { workspace = true }
nyanpasu-core = { path = '../nyanpasu-core' }
anyhow = '1'
ractor = '0.16'
struct-patch = '0.14'
tokio = { workspace = true, features = ['full'] }
tokio-util = { version = '0.7', features = ['rt'] }
tracing = { workspace = true }
nyanpasu-config = { path = '../nyanpasu-config' }

serde = { version = '1', features = ['derive'] }
serde_yaml = { version = '0.10', package = 'serde_yaml_ng', git = 'https://github.com/libnyanpasu/serde-yaml-ng.git', rev = '363da138dc97f90ef0a356f971c2dc1d8fe04c9e', features = [
  'specta'
] }
specta = { version = '^2.0.0-rc.25' }
snafu = { workspace = true }
strum = { version = '0.28', features = ['derive'] }

[dev-dependencies]
tempfile = '3'
serde_json = { version = '1', features = ['preserve_order'] }
