/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as legacyRouteRouteImport } from './pages/(legacy)/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as legacySettingsRouteImport } from './pages/(legacy)/settings'
import { Route as legacyRulesRouteImport } from './pages/(legacy)/rules'
import { Route as legacyProxiesRouteImport } from './pages/(legacy)/proxies'
import { Route as legacyProvidersRouteImport } from './pages/(legacy)/providers'
import { Route as legacyProfilesRouteImport } from './pages/(legacy)/profiles'
import { Route as legacyLogsRouteImport } from './pages/(legacy)/logs'
import { Route as legacyDashboardRouteImport } from './pages/(legacy)/dashboard'
import { Route as legacyConnectionsRouteImport } from './pages/(legacy)/connections'

const legacyRouteRoute = legacyRouteRouteImport.update({
  id: '/(legacy)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const legacySettingsRoute = legacySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyRulesRoute = legacyRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyProxiesRoute = legacyProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyProvidersRoute = legacyProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyProfilesRoute = legacyProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyLogsRoute = legacyLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyDashboardRoute = legacyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => legacyRouteRoute,
} as any)
const legacyConnectionsRoute = legacyConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => legacyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof legacyConnectionsRoute
  '/dashboard': typeof legacyDashboardRoute
  '/logs': typeof legacyLogsRoute
  '/profiles': typeof legacyProfilesRoute
  '/providers': typeof legacyProvidersRoute
  '/proxies': typeof legacyProxiesRoute
  '/rules': typeof legacyRulesRoute
  '/settings': typeof legacySettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof legacyConnectionsRoute
  '/dashboard': typeof legacyDashboardRoute
  '/logs': typeof legacyLogsRoute
  '/profiles': typeof legacyProfilesRoute
  '/providers': typeof legacyProvidersRoute
  '/proxies': typeof legacyProxiesRoute
  '/rules': typeof legacyRulesRoute
  '/settings': typeof legacySettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(legacy)': typeof legacyRouteRouteWithChildren
  '/(legacy)/connections': typeof legacyConnectionsRoute
  '/(legacy)/dashboard': typeof legacyDashboardRoute
  '/(legacy)/logs': typeof legacyLogsRoute
  '/(legacy)/profiles': typeof legacyProfilesRoute
  '/(legacy)/providers': typeof legacyProvidersRoute
  '/(legacy)/proxies': typeof legacyProxiesRoute
  '/(legacy)/rules': typeof legacyRulesRoute
  '/(legacy)/settings': typeof legacySettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/dashboard'
    | '/logs'
    | '/profiles'
    | '/providers'
    | '/proxies'
    | '/rules'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/dashboard'
    | '/logs'
    | '/profiles'
    | '/providers'
    | '/proxies'
    | '/rules'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(legacy)'
    | '/(legacy)/connections'
    | '/(legacy)/dashboard'
    | '/(legacy)/logs'
    | '/(legacy)/profiles'
    | '/(legacy)/providers'
    | '/(legacy)/proxies'
    | '/(legacy)/rules'
    | '/(legacy)/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  legacyRouteRoute: typeof legacyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(legacy)': {
      id: '/(legacy)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/settings': {
      id: '/(legacy)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof legacySettingsRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/rules': {
      id: '/(legacy)/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof legacyRulesRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/proxies': {
      id: '/(legacy)/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof legacyProxiesRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/providers': {
      id: '/(legacy)/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof legacyProvidersRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/profiles': {
      id: '/(legacy)/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof legacyProfilesRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/logs': {
      id: '/(legacy)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof legacyLogsRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/dashboard': {
      id: '/(legacy)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof legacyDashboardRouteImport
      parentRoute: typeof legacyRouteRoute
    }
    '/(legacy)/connections': {
      id: '/(legacy)/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof legacyConnectionsRouteImport
      parentRoute: typeof legacyRouteRoute
    }
  }
}

interface legacyRouteRouteChildren {
  legacyConnectionsRoute: typeof legacyConnectionsRoute
  legacyDashboardRoute: typeof legacyDashboardRoute
  legacyLogsRoute: typeof legacyLogsRoute
  legacyProfilesRoute: typeof legacyProfilesRoute
  legacyProvidersRoute: typeof legacyProvidersRoute
  legacyProxiesRoute: typeof legacyProxiesRoute
  legacyRulesRoute: typeof legacyRulesRoute
  legacySettingsRoute: typeof legacySettingsRoute
}

const legacyRouteRouteChildren: legacyRouteRouteChildren = {
  legacyConnectionsRoute: legacyConnectionsRoute,
  legacyDashboardRoute: legacyDashboardRoute,
  legacyLogsRoute: legacyLogsRoute,
  legacyProfilesRoute: legacyProfilesRoute,
  legacyProvidersRoute: legacyProvidersRoute,
  legacyProxiesRoute: legacyProxiesRoute,
  legacyRulesRoute: legacyRulesRoute,
  legacySettingsRoute: legacySettingsRoute,
}

const legacyRouteRouteWithChildren = legacyRouteRoute._addFileChildren(
  legacyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  legacyRouteRoute: legacyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
