name: 🐞 Bug report
description: Create a bug report
labels:
  - 'T: Bug'
  - 'S: Untriaged'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue. Please write a concise and appropriate title for this issue in the title field, and then fill out the form below step by step.
        _Contents marked with an asterisk (*) are required._

  - type: checkboxes
    id: check
    attributes:
      label: Self-review steps
      description: Review the following items carefully and confirm each one. Issues where the actual situation does not match the required items may be closed.
      options:
        - label: I realize that if I do not carefully review these steps and write the issue description thoroughly, my issue may be closed.
          required: true
        - label: I searched on [Issue list](https://github.com/libnyanpasu/clash-nyanpasu/issues) and [Discussions](https://github.com/libnyanpasu/clash-nyanpasu/discussions), no duplicate or related open contents has been found.
          required: true
        - label: I ensure that this issue contains only one bug topic. If there are multiple topics, I will create separate issues for each one.
          required: true
        - label: I read and understood the contents of [Q&A Convention](https://nyanpasu.org/others/issues/) and [FAQ](https://nyanpasu.org/others/faq/).
          required: true
        - label: I tried the latest Beta / Nightly version, but this bug has not been fixed.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/libnyanpasu/clash-nyanpasu/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I want to submit a pull request to resolve this issue.
          required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Step to reproduce
      description: Please write down the reproduction steps here.
      placeholder: |
        1. 
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what should happened here.
      placeholder: It should be ...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Describe what actually happened here.
      placeholder: Actually it ...
    validations:
      required: true

  - type: textarea
    id: env_infos
    attributes:
      label: Environment information
      description: Provide your environment information here — operating system version, Clash Nyanpasu version, Clash core, and its version, etc.
      placeholder: |
        You can enter the above information manually,
        or click the “Help” → “Report issue” button in the toolbar of the Nyanpasu desktop view to open a new page that automatically fills in more detailed information.
    validations:
      required: true

  - type: textarea
    id: more
    attributes:
      label: Additional details
      description: Describe additional details here.
      placeholder: Additional details and attachments, such as screenshots, videos, etc.
    validations:
      required: false

  - type: textarea
    id: log
    attributes:
      label: App logs
      description: |
        If you are not sure whether you should provide logs, leave this field blank. Maintainers will decide whether to ask you for logs based on the situation.
        If you want to provide logs, make sure you have removed all sensitive information and that the log level is set to `Trace` or `Debug`. See [FAQ - Config/Log Dir](https://nyanpasu.org/others/faq/#2-where-is-the-clash-nyanpasu-configlogs-directory).
        If the logs are too long, you can use [Gist](https://gist.github.com/) or [Hastebin](https://hastebin.com/) and provide a link.
        You can also generate a log archive by clicking “Help” → “Collect logs” in the toolbar of the Nyanpasu desktop view, then drag it here after reviewing the logs and removing any sensitive information.
      placeholder: Should be a link, a code block, or an archive file — if available.
    validations:
      required: false
