// This file has been generated by Specta. Do not edit this file manually.
export type ActivateProfileInput = {
	profileId: string | null,
};

export type ActivateProfileResult = { status: "committed"; value: null; commits: CommitReceipt[]; notifications_pending: boolean } | { status: "committed_degraded"; value: null; commits: CommitReceipt[]; notifications_pending: boolean; degradations: Degradation[] };

export type ClashConnectionsConnectorState = "disconnected" | "connecting" | "connected";

export type ClashWsConnectionSnapshot = {
	downloadTotal: number,
	uploadTotal: number,
	downloadSpeed: number,
	uploadSpeed: number,
	memory: number | null,
	connections: any | null,
};

export type ClashWsEvent = {
	sequence: number,
	update: ClashWsUpdate,
};

export type ClashWsKind = "connections" | "logs" | "traffic" | "memory";

export type ClashWsLog = {
	type: string,
	time: string | null,
	payload: string,
};

export type ClashWsMemory = {
	inuse: number,
	oslimit: number,
};

export type ClashWsRecording = {
	connections: boolean,
	logs: boolean,
	traffic: boolean,
	memory: boolean,
};

export type ClashWsSnapshot = {
	sequence: number,
	state: ClashConnectionsConnectorState,
	recording: ClashWsRecording,
	connections: ClashWsConnectionSnapshot[],
	logs: ClashWsLog[],
	traffic: ClashWsTraffic[],
	memory: ClashWsMemory[],
};

export type ClashWsTraffic = {
	up: number,
	down: number,
};

export type ClashWsUpdate = { kind: "reset"; data: ClashWsSnapshot } | { kind: "state_changed"; data: ClashConnectionsConnectorState } | { kind: "connections_updated"; data: ClashWsConnectionSnapshot } | { kind: "log_appended"; data: ClashWsLog } | { kind: "traffic_updated"; data: ClashWsTraffic } | { kind: "memory_updated"; data: ClashWsMemory } | { kind: "recording_changed"; data: ClashWsRecording } | { kind: "history_cleared"; data: ClashWsKind };

/**  A source commit and its critical runtime result. Peripheral owners settle separately. */
export type CommitReceipt = {
	operation_id: string | null,
	domain: string,
	source_version: number,
	runtime: RuntimeCommitStatus,
};

/**  Structured committed-degraded detail surfaced over IPC / Specta. */
export type Degradation = {
	phase: DegradationPhase,
	/**  Stable snake_case code string (not a free-form English phrase). */
	code: string,
	message: string,
	retryable: boolean,
};

/**  Public degradation phases for mutation outcomes. Serde/Specta use snake_case. */
export type DegradationPhase = "legacy_mirror" | "profile_materialization" | "runtime_build" | "runtime_check" | "runtime_promote" | "runtime_publish" | "runtime_apply" | "core_rollback" | "system_effect" | "ui_effect";

export type EmptyInput = Record<string, never>;

export type ProfileSummary = {
	id: string,
	name: string,
	active: boolean,
};

export type ProfilesList = {
	current: string | null,
	items: ProfileSummary[],
};

export type RuntimeCommitStatus = "applied" | "deferred" | "saved_inactive" | "unchanged" | "pending" | "recovery_required";
