/* oxlint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'
import * as __TAURI_EVENT from '@tauri-apps/api/event'

/** Commands */
export const commands = {
  /**
   *  get the system proxy
   *  server field is the combination of host and port
   */
  getSysProxy: () =>
    typedError<GetSysProxyResponse, string>(__TAURI_INVOKE('get_sys_proxy')),
  flushSystemDnsCache: () =>
    typedError<null, string>(__TAURI_INVOKE('flush_system_dns_cache')),
  openAppConfigDir: () =>
    typedError<null, string>(__TAURI_INVOKE('open_app_config_dir')),
  openAppDataDir: () =>
    typedError<null, string>(__TAURI_INVOKE('open_app_data_dir')),
  openLogsDir: () => typedError<null, string>(__TAURI_INVOKE('open_logs_dir')),
  openWebUrl: (url: string) =>
    typedError<null, string>(__TAURI_INVOKE('open_web_url', { url })),
  openCoreDir: () => typedError<null, string>(__TAURI_INVOKE('open_core_dir')),
  /**  restart the sidecar */
  restartSidecar: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_sidecar')),
  getClashInfo: () =>
    typedError<ClashInfo, string>(__TAURI_INVOKE('get_clash_info')),
  getClashLogs: () =>
    typedError<string[], string>(__TAURI_INVOKE('get_clash_logs')),
  /**  patch clash runtime config */
  patchClashConfig: (payload: PatchRuntimeConfig_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_clash_config', { payload })),
  changeClashCore: (
    clashCore:
      | 'clash'
      | 'clash-premium'
      | 'clash-rs'
      | 'mihomo'
      | 'clash-meta'
      | 'mihomo-alpha'
      | 'clash-rs-alpha'
      | 'meow'
      | null,
  ) =>
    typedError<null, string>(
      __TAURI_INVOKE('change_clash_core', { clashCore }),
    ),
  /**  get the runtime config */
  getRuntimeConfig: () =>
    typedError<any | null, string>(__TAURI_INVOKE('get_runtime_config')),
  getRuntimeYaml: () =>
    typedError<string, string>(__TAURI_INVOKE('get_runtime_yaml')),
  getRuntimeExists: () =>
    typedError<string[], string>(__TAURI_INVOKE('get_runtime_exists')),
  getPostprocessingOutput: () =>
    typedError<PostProcessingOutput, string>(
      __TAURI_INVOKE('get_postprocessing_output'),
    ),
  clashApiGetProxyDelay: (
    name: string,
    provider: string | null,
    url: string | null,
  ) =>
    typedError<DelayRes, string>(
      __TAURI_INVOKE('clash_api_get_proxy_delay', { name, provider, url }),
    ),
  clashApiGetConfigs: () =>
    typedError<ClashConfig, string>(__TAURI_INVOKE('clash_api_get_configs')),
  clashApiDeleteConnections: (id: string | null) =>
    typedError<null, string>(
      __TAURI_INVOKE('clash_api_delete_connections', { id }),
    ),
  clashApiGetVersion: () =>
    typedError<ClashVersion, string>(__TAURI_INVOKE('clash_api_get_version')),
  clashApiGetRules: () =>
    typedError<RulesRes, string>(__TAURI_INVOKE('clash_api_get_rules')),
  clashApiGetProvidersRules: () =>
    typedError<ProvidersRulesRes, string>(
      __TAURI_INVOKE('clash_api_get_providers_rules'),
    ),
  clashApiUpdateProvidersRules: (name: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('clash_api_update_providers_rules', { name }),
    ),
  clashApiGetGroupDelay: (group: string, url: string | null) =>
    typedError<{ [key in string]: number }, string>(
      __TAURI_INVOKE('clash_api_get_group_delay', { group, url }),
    ),
  clashApiGetProvidersProxies: () =>
    typedError<ProvidersProxiesRes_Serialize, string>(
      __TAURI_INVOKE('clash_api_get_providers_proxies'),
    ),
  invokeUwpTool: () =>
    typedError<null, string>(__TAURI_INVOKE('invoke_uwp_tool')),
  fetchLatestCoreVersions: () =>
    typedError<ManifestVersionLatest, string>(
      __TAURI_INVOKE('fetch_latest_core_versions'),
    ),
  updateCore: (coreType: ClashCore_Deserialize) =>
    typedError<number, string>(__TAURI_INVOKE('update_core', { coreType })),
  inspectUpdater: (updaterId: number) =>
    typedError<UpdaterSummary, string>(
      __TAURI_INVOKE('inspect_updater', { updaterId }),
    ),
  getCoreVersion: (coreType: ClashCore_Deserialize) =>
    typedError<string, string>(
      __TAURI_INVOKE('get_core_version', { coreType }),
    ),
  collectLogs: () => typedError<null, string>(__TAURI_INVOKE('collect_logs')),
  getVergeConfig: () =>
    typedError<IVerge_Serialize, string>(__TAURI_INVOKE('get_verge_config')),
  patchVergeConfig: (payload: IVerge_Deserialize) =>
    typedError<null, string>(__TAURI_INVOKE('patch_verge_config', { payload })),
  getHotkeyFunctions: () => __TAURI_INVOKE<string[]>('get_hotkey_functions'),
  getProfiles: () =>
    typedError<ProfileDocument_Serialize, string>(
      __TAURI_INVOKE('get_profiles'),
    ),
  /**
   *  Rebuild-only command: there is no prior state commit, so a failure is a
   *  plain error — the committed/degraded model (spec §6.2) does not apply.
   */
  enhanceProfiles: () =>
    typedError<null, string>(__TAURI_INVOKE('enhance_profiles')),
  importProfile: (
    url: string,
    name: string | null,
    option: {
      user_agent?: string | null
      with_proxy: boolean | null
      self_proxy: boolean | null
      update_interval_minutes: number | null
    } | null,
  ) =>
    typedError<MutationOutcome<ProfileId>, string>(
      __TAURI_INVOKE('import_profile', { url, name, option }),
    ),
  /**
   *  Take and clear the pending cold-start deep link, if any. Called once by the
   *  frontend during startup.
   */
  getPendingDeepLink: () =>
    typedError<string | null, string>(__TAURI_INVOKE('get_pending_deep_link')),
  /**  create a new profile */
  createProfile: (
    request: NewProfileRequest_Deserialize,
    fileData: string | null,
  ) =>
    typedError<MutationOutcome<ProfileId>, string>(
      __TAURI_INVOKE('create_profile', { request, fileData }),
    ),
  reorderProfile: (activeId: ProfileId, overId: ProfileId) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('reorder_profile', { activeId, overId }),
    ),
  reorderProfilesByList: (list: ProfileId[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('reorder_profiles_by_list', { list }),
    ),
  updateProfile: (
    uid: ProfileId,
    option: {
      user_agent?: string | null
      with_proxy: boolean | null
      self_proxy: boolean | null
      update_interval_minutes: number | null
    } | null,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('update_profile', { uid, option }),
    ),
  deleteProfile: (uid: ProfileId) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('delete_profile', { uid }),
    ),
  activateProfile: (uid: string | null) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('activate_profile', { uid }),
    ),
  setGlobalTransforms: (ids: ProfileId[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('set_global_transforms', { ids }),
    ),
  setProfileValidFields: (fields: string[]) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('set_profile_valid_fields', { fields }),
    ),
  patchProfileMetadata: (
    uid: ProfileId,
    patch: ProfileMetadataPatch_Deserialize,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('patch_profile_metadata', { uid, patch }),
    ),
  patchRemoteProfileOptions: (
    uid: ProfileId,
    patch: RemoteProfileOptionsPatch_Deserialize,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('patch_remote_profile_options', { uid, patch }),
    ),
  replaceProfileDefinition: (
    uid: ProfileId,
    definition: ProfileDefinition_Deserialize,
  ) =>
    typedError<MutationOutcome<null>, string>(
      __TAURI_INVOKE('replace_profile_definition', { uid, definition }),
    ),
  viewProfile: (uid: ProfileId) =>
    typedError<null, string>(__TAURI_INVOKE('view_profile', { uid })),
  readProfileFile: (uid: ProfileId) =>
    typedError<string, string>(__TAURI_INVOKE('read_profile_file', { uid })),
  saveProfileFile: (uid: ProfileId, fileData: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_profile_file', { uid, fileData }),
    ),
  getCustomAppDir: () =>
    typedError<string | null, string>(__TAURI_INVOKE('get_custom_app_dir')),
  setCustomAppDir: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE('set_custom_app_dir', { path })),
  statusService: () =>
    typedError<ServiceStatusInfo_Serialize, string>(
      __TAURI_INVOKE('status_service'),
    ),
  installService: () =>
    typedError<null, string>(__TAURI_INVOKE('install_service')),
  uninstallService: () =>
    typedError<null, string>(__TAURI_INVOKE('uninstall_service')),
  startService: () => typedError<null, string>(__TAURI_INVOKE('start_service')),
  stopService: () => typedError<null, string>(__TAURI_INVOKE('stop_service')),
  restartService: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_service')),
  isPortable: () => typedError<boolean, string>(__TAURI_INVOKE('is_portable')),
  getProxies: () =>
    typedError<Proxies_Serialize, string>(__TAURI_INVOKE('get_proxies')),
  selectProxy: (group: string, name: string) =>
    typedError<null, string>(__TAURI_INVOKE('select_proxy', { group, name })),
  updateProxyProvider: (name: string) =>
    typedError<null, string>(__TAURI_INVOKE('update_proxy_provider', { name })),
  restartApplication: () =>
    typedError<null, string>(__TAURI_INVOKE('restart_application')),
  collectEnvs: () =>
    typedError<EnvInfo, string>(__TAURI_INVOKE('collect_envs')),
  getServerPort: () =>
    typedError<number, string>(__TAURI_INVOKE('get_server_port')),
  setTrayIcon: (mode: TrayIcon, path: string | null) =>
    typedError<null, string>(__TAURI_INVOKE('set_tray_icon', { mode, path })),
  isTrayIconSet: (mode: TrayIcon) =>
    typedError<boolean, string>(__TAURI_INVOKE('is_tray_icon_set', { mode })),
  getCoreStatus: () =>
    typedError<CoreStatusInfo, string>(__TAURI_INVOKE('get_core_status')),
  urlDelayTest: (url: string, expectedStatus: number) =>
    typedError<number | null, string>(
      __TAURI_INVOKE('url_delay_test', { url, expectedStatus }),
    ),
  getIpsbAsn: () => typedError<any, string>(__TAURI_INVOKE('get_ipsb_asn')),
  openThat: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE('open_that', { path })),
  isAppimage: () => typedError<boolean, string>(__TAURI_INVOKE('is_appimage')),
  getServiceInstallPrompt: () =>
    typedError<string, string>(__TAURI_INVOKE('get_service_install_prompt')),
  cleanupProcesses: () =>
    typedError<null, string>(__TAURI_INVOKE('cleanup_processes')),
  getStorageItem: (key: string) =>
    typedError<string | null, string>(
      __TAURI_INVOKE('get_storage_item', { key }),
    ),
  setStorageItem: (key: string, value: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('set_storage_item', { key, value }),
    ),
  removeStorageItem: (key: string) =>
    typedError<null, string>(__TAURI_INVOKE('remove_storage_item', { key })),
  /**
   *  Debug: returns all frontend KV entries (keys with the `web:` prefix).
   *  Internal storage entries used by other subsystems are excluded.
   */
  getAllStorageItems: () =>
    typedError<StorageEntry[], string>(__TAURI_INVOKE('get_all_storage_items')),
  /**
   *  Debug: clears all frontend KV entries (keys with the `web:` prefix).
   *  Internal storage entries used by other subsystems are left intact.
   */
  clearStorage: () => typedError<null, string>(__TAURI_INVOKE('clear_storage')),
  getHotkeys: () =>
    typedError<string[] | null, string>(__TAURI_INVOKE('get_hotkeys')),
  setHotkeys: (hotkeys: string[]) =>
    typedError<null, string>(__TAURI_INVOKE('set_hotkeys', { hotkeys })),
  mutateProxies: () =>
    typedError<Proxies_Serialize, string>(__TAURI_INVOKE('mutate_proxies')),
  getCoreDir: () => typedError<string, string>(__TAURI_INVOKE('get_core_dir')),
  getClashWsConnectionsState: () =>
    typedError<ClashConnectionsConnectorState, string>(
      __TAURI_INVOKE('get_clash_ws_connections_state'),
    ),
  getClashWsSnapshot: () =>
    typedError<ClashWsSnapshot, string>(
      __TAURI_INVOKE('get_clash_ws_snapshot'),
    ),
  setClashWsRecording: (kind: ClashWsKind, enabled: boolean) =>
    typedError<ClashWsRecording, string>(
      __TAURI_INVOKE('set_clash_ws_recording', { kind, enabled }),
    ),
  clearClashWsHistory: (kind: ClashWsKind) =>
    typedError<null, string>(
      __TAURI_INVOKE('clear_clash_ws_history', { kind }),
    ),
  checkUpdate: () =>
    typedError<
      {
        rid: number
        available: boolean
        current_version: string
        version: string
        date: string | null
        body: string | null
        raw_json: any
      } | null,
      string
    >(__TAURI_INVOKE('check_update')),
  saveWindowSizeState: (label: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_window_size_state', { label }),
    ),
  createMainWindow: () =>
    typedError<null, string>(__TAURI_INVOKE('create_main_window')),
  createDebugTrayMenuWindow: () =>
    typedError<null, string>(__TAURI_INVOKE('create_debug_tray_menu_window')),
  createEditorWindow: (windowType: EditorWindowType, uid: string | null) =>
    typedError<null, string>(
      __TAURI_INVOKE('create_editor_window', { windowType, uid }),
    ),
  copyClashEnv: (envType: CopyEnvOption) =>
    __TAURI_INVOKE<void>('copy_clash_env', { envType }),
  quitApplication: () => __TAURI_INVOKE<void>('quit_application'),
  getSystemAccentColor: () =>
    typedError<string | null, string>(
      __TAURI_INVOKE('get_system_accent_color'),
    ),
}

/** Events */
export const events = {
  clashConnectionsEvent: makeEvent<ClashConnectionsEvent>(
    'clash-connections-event',
  ),
  clashWsEvent: makeEvent<ClashWsEvent>('clash-ws-event'),
  coreStatusChangedEvent: makeEvent<CoreStatusChangedEvent>(
    'core-status-changed-event',
  ),
  schemeRequestReceivedEvent: makeEvent<SchemeRequestReceivedEvent>(
    'scheme-request-received-event',
  ),
  serviceStatusChangedEvent: makeEvent<ServiceStatusChangedEvent_Deserialize>(
    'service-status-changed-event',
  ),
  storageValueChangedEvent: makeEvent<StorageValueChangedEvent>(
    'storage-value-changed-event',
  ),
  windowMessageEvent: makeEvent<WindowMessageEvent>('window-message-event'),
  windowReadyEvent: makeEvent<WindowReadyEvent>('window-ready-event'),
}

/* Types */
export type BreakWhenProxyChange = 'none' | 'chain' | 'all'

export type BuildInfo = {
  app_name: string
  app_version: string
  pkg_version: string
  commit_hash: string
  commit_author: string
  commit_date: string
  build_date: string
  build_profile: string
  build_platform: string
  rustc_version: string
  llvm_version: string
}

export type ClashConfig = {
  port: number | null
  mode: string | null
  ipv6: boolean | null
  'socket-port': number | null
  'allow-lan': boolean | null
  'log-level': string | null
  'mixed-port': number | null
  'redir-port': number | null
  'socks-port': number | null
  'tproxy-port': number | null
  'external-controller': string | null
  secret: string | null
}

export type ClashConnectionsConnectorEvent =
  | { kind: 'state_changed'; data: ClashConnectionsConnectorState }
  | { kind: 'update'; data: ClashConnectionsInfo }

export type ClashConnectionsConnectorState =
  | 'disconnected'
  | 'connecting'
  | 'connected'

export type ClashConnectionsEvent = ClashConnectionsConnectorEvent

export type ClashConnectionsInfo = {
  downloadTotal: number
  uploadTotal: number
  downloadSpeed: number
  uploadSpeed: number
}

export type ClashCore = ClashCore_Serialize | ClashCore_Deserialize

export type ClashCoreType =
  | 'mihomo'
  | 'mihomo-alpha'
  | 'clash-rs'
  | 'clash-rs-alpha'
  | 'clash'
  | 'meow'

export type ClashCore_Deserialize =
  | 'clash'
  | 'clash-premium'
  | 'clash-rs'
  | 'mihomo'
  | 'clash-meta'
  | 'mihomo-alpha'
  | 'clash-rs-alpha'
  | 'meow'

export type ClashCore_Serialize =
  | 'clash'
  | 'clash-rs'
  | 'mihomo'
  | 'mihomo-alpha'
  | 'clash-rs-alpha'
  | 'meow'

export type ClashInfo = {
  /**  clash core port */
  port: number
  /**  same as `external-controller` */
  server: string
  /**  clash secret */
  secret: string | null
}

export type ClashRule = {
  type: string
  payload: string
  proxy: string
}

export type ClashStrategy = {
  external_controller_port_strategy: ExternalControllerPortStrategy
}

export type ClashVersion = {
  version: string
  premium: boolean | null
  meta: boolean | null
}

export type ClashWsConnectionSnapshot = {
  downloadTotal: number
  uploadTotal: number
  downloadSpeed: number
  uploadSpeed: number
  memory: number | null
  connections: any | null
}

export type ClashWsEvent =
  | { kind: 'state_changed'; data: ClashConnectionsConnectorState }
  | { kind: 'connections_updated'; data: ClashWsConnectionSnapshot }
  | { kind: 'log_appended'; data: ClashWsLog }
  | { kind: 'traffic_updated'; data: ClashWsTraffic }
  | { kind: 'memory_updated'; data: ClashWsMemory }
  | { kind: 'recording_changed'; data: ClashWsRecording }
  | { kind: 'history_cleared'; data: ClashWsKind }

export type ClashWsKind = 'connections' | 'logs' | 'traffic' | 'memory'

export type ClashWsLog = {
  type: string
  time: string | null
  payload: string
}

export type ClashWsMemory = {
  inuse: number
  oslimit: number
}

export type ClashWsRecording = {
  connections: boolean
  logs: boolean
  traffic: boolean
  memory: boolean
}

export type ClashWsSnapshot = {
  state: ClashConnectionsConnectorState
  recording: ClashWsRecording
  connections: ClashWsConnectionSnapshot[]
  logs: ClashWsLog[]
  traffic: ClashWsTraffic[]
  memory: ClashWsMemory[]
}

export type ClashWsTraffic = {
  up: number
  down: number
}

export type CompositionConfig =
  | CompositionConfig_Serialize
  | CompositionConfig_Deserialize

export type CompositionConfig_Deserialize = {
  /**
   *  Optional full config seed.
   *
   *  - Some(id): inherit a full scoped config from `id`.
   *  - None: start from a clean config seed and only extend proxies/nodes from
   *    `extend_proxies_from` before running `transforms`.
   */
  base?: ProfileId | null
  /**  Members that only contribute their scoped-result proxies/nodes. */
  extend_proxies_from?: ProfileId[]
  /**  Post-processing transforms after proxies have been extended. */
  transforms?: ProfileId[]
}

export type CompositionConfig_Serialize = {
  /**
   *  Optional full config seed.
   *
   *  - Some(id): inherit a full scoped config from `id`.
   *  - None: start from a clean config seed and only extend proxies/nodes from
   *    `extend_proxies_from` before running `transforms`.
   */
  base?: ProfileId | null
  /**  Members that only contribute their scoped-result proxies/nodes. */
  extend_proxies_from?: ProfileId[]
  /**  Post-processing transforms after proxies have been extended. */
  transforms?: ProfileId[]
}

export type CompositionMemberRole = 'base' | 'contributor'

/**  A profile that can produce a complete config and can be selected by current. */
export type ConfigDefinition =
  | ConfigDefinition_Serialize
  | ConfigDefinition_Deserialize

/**  A profile that can produce a complete config and can be selected by current. */
export type ConfigDefinition_Deserialize =
  /**  A config parsed from a locally materialized file. */
  | ({
      type: 'file'
      source: ProfileSource_Deserialize
      transforms?: ProfileId[]
    } & { base?: never; extend_proxies_from?: never })
  /**  A config composed from an optional full base and proxy contributors. */
  | ({
      type: 'composition'
      base?: ProfileId | null
      extend_proxies_from?: ProfileId[]
      transforms?: ProfileId[]
    } & { source?: never })

/**  A profile that can produce a complete config and can be selected by current. */
export type ConfigDefinition_Serialize =
  /**  A config parsed from a locally materialized file. */
  | ({
      type: 'file'
      source: ProfileSource_Serialize
      transforms?: ProfileId[]
    } & { base?: never; extend_proxies_from?: never })
  /**  A config composed from an optional full base and proxy contributors. */
  | ({
      type: 'composition'
      base?: ProfileId | null
      extend_proxies_from?: ProfileId[]
      transforms?: ProfileId[]
    } & { source?: never })

/**
 *  Identity of the config the running core actually adopted.
 *
 *  `source_hash` is computed over the caller's own file and `effective_hash`
 *  over the canonical form the core is running, both FNV-1a over canonical
 *  YAML. A caller that holds the source file can therefore confirm the
 *  service read the same bytes it wrote, without reimplementing the hash.
 *  The manager's private runtime copy path is deliberately not exposed: it
 *  lives in a 0o700 directory the caller cannot read, so it would only
 *  mislead.
 */
export type ConfigRevisionInfo = {
  epoch: number
  generation: number
  source_hash: string
  effective_hash: string
}

export type CopyEnvOption = 'shell' | 'cmd' | 'pwsh'

/**
 *  The core's control endpoint, as the manager resolved it.
 *
 *  A deliberately separate type from `clash_api::Host`: clash-api is an
 *  internal dependency of the core manager and must not leak into the wire
 *  dependency tree. The controller secret is never carried here. Clients read
 *  applied credentials through the private `/v2/core/api-connection` endpoint;
 *  the IPC transport's authorization gate is the socket ACL.
 */
export type CoreControllerInfo =
  | ({ NamedPipe: string } & { Http?: never; UnixSocket?: never })
  | ({ UnixSocket: string } & { Http?: never; NamedPipe?: never })
  /**  Normalized base URL with any credentials removed. */
  | ({ Http: string } & { NamedPipe?: never; UnixSocket?: never })

/**
 *  The manager's health observation for the active core. Absent while the
 *  core is stopping or stopped.
 */
export type CoreHealthInfo = {
  state: CoreHealthState
  /**  Unix milliseconds of the last health-state transition. */
  changed_at: number
  consecutive_failures: number
  /**  Last probe failure detail, capped by the manager at 512 bytes. */
  last_error: string | null
  /**  Unix milliseconds of the last successful probe. */
  last_success_at: number | null
}

/**  Health observation state for the active core. */
export type CoreHealthState = 'Starting' | 'Healthy' | 'Unhealthy'

export type CoreInfos = CoreInfos_Serialize | CoreInfos_Deserialize

export type CoreInfos_Deserialize = {
  instance_id?: string | null
  type: CoreType | null
  state: CoreState
  state_changed_at: number
  config_path: string | null
  /**
   *  Omitted rather than null when absent, so a payload carrying none of
   *  the fields below is byte-identical to the pre-S7 wire format.
   */
  controller?: CoreControllerInfo | null
  health?: CoreHealthInfo | null
  revision?: ConfigRevisionInfo | null
  detail?: CoreStateDetail | null
}

export type CoreInfos_Serialize = {
  instance_id?: string | null
  type: CoreType | null
  state: CoreState
  state_changed_at: number
  config_path: string | null
  /**
   *  Omitted rather than null when absent, so a payload carrying none of
   *  the fields below is byte-identical to the pre-S7 wire format.
   */
  controller?: CoreControllerInfo | null
  health?: CoreHealthInfo | null
  revision?: ConfigRevisionInfo | null
  detail?: CoreStateDetail | null
}

export type CoreState = 'Running' | { Stopped: string | null }

/**
 *  The core's full lifecycle state.
 *
 *  [`CoreState`] is a two-valued projection kept for wire compatibility: it
 *  reports `Starting` and `Restarting` as `Stopped(None)`, so a crash loop is
 *  indistinguishable from a real stop. This is the faithful view; prefer it
 *  when present.
 */
export type CoreStateDetail =
  | ({
      Stopped: {
        reason: string | null
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Starting: {
        epoch: number
      }
    } & {
      Restarting?: never
      Running?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Running: {
        epoch: number
        pid: number
      }
    } & {
      Restarting?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Restarting: {
        epoch: number
        attempt: number
      }
    } & {
      Running?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Switching: {
        from: number | null
        to: number
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
    })
  | ({
      Stopping: {
        epoch: number
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopped?: never
      Switching?: never
    })

export type CoreStatusChangedEvent = CoreStatusInfo

export type CoreStatusInfo = {
  host: ExecutionHost
  connectivity: EndpointConnectivity
  generation: number
  state: CoreStateDetail | null
  state_changed_at: number
  revision: RevisionIdInfo | null
  healthy: boolean | null
}

export type CoreType = { clash: ClashCoreType } | 'singbox'

/**  Structured committed-degraded detail surfaced over IPC / Specta. */
export type Degradation = {
  phase: DegradationPhase
  /**  Stable snake_case code string (not a free-form English phrase). */
  code: string
  message: string
  retryable: boolean
}

/**  Public degradation phases for mutation outcomes. Serde/Specta use snake_case. */
export type DegradationPhase =
  | 'legacy_mirror'
  | 'profile_materialization'
  | 'runtime_build'
  | 'runtime_check'
  | 'runtime_promote'
  | 'runtime_publish'
  | 'runtime_apply'
  | 'core_rollback'
  | 'system_effect'
  | 'ui_effect'

export type DelayRes = {
  delay: number
}

export type DeviceInfo = {
  /**  Device name, such as "Intel Core i5-8250U CPU @ 1.60GHz x 8" */
  cpu: string[]
  /**
   *  GPU name, such as "Intel UHD Graphics 620 (Kabylake GT2)"
   *  Memory size in bytes
   */
  memory: string
}

/**  A snapshot of a download session's progress, polled by IPC. */
export type DownloadStatus = {
  state: DownloaderState
  downloaded: number
  total: number
  speed: number | null
}

/**  The high-level state of a download session. */
export type DownloaderState =
  | 'idle'
  | 'downloading'
  | { failed: string }
  | 'finished'

/**
 *  Type of content the editor window displays.
 *  Used to derive the window label (for singleton logic) and URL path params.
 */
export type EditorWindowType = 'profile' | 'css-editor'

export type EndpointConnectivity =
  | { kind: 'connected' }
  | { kind: 'shut_down' }
  | { kind: 'handing_off'; from: ExecutionHost; to: ExecutionHost }
  /**
   *  The endpoint is unreachable. `desired` names the committed host; the
   *  router never falls back on its own.
   */
  | { kind: 'degraded'; desired: ExecutionHost; reason: string }

export type EnvInfo = {
  os: string
  arch: string
  core: { [key in string]: string }
  device: DeviceInfo
  build_info: {
    app_name: string
    app_version: string
    pkg_version: string
    commit_hash: string
    commit_author: string
    commit_date: string
    build_date: string
    build_profile: string
    build_platform: string
    rustc_version: string
    llvm_version: string
  }
}

/**
 *  Which controller owns the runtime. The app perceives the difference in
 *  exactly two places: this tag on the endpoint slot, and the handoff
 *  protocol.
 */
export type ExecutionHost = 'local' | 'service'

export type ExternalControllerPortStrategy =
  | 'fixed'
  | 'random'
  | 'allow_fallback'

export type ExternalMode = 'symlink' | 'mirror'

/**  An absolute path outside the managed profile directory. */
export type ExternalProfilePath = string

export type FileConfig = FileConfig_Serialize | FileConfig_Deserialize

export type FileConfig_Deserialize = {
  source: ProfileSource_Deserialize
  /**  Scoped post-processing transforms. */
  transforms?: ProfileId[]
}

export type FileConfig_Serialize = {
  source: ProfileSource_Serialize
  /**  Scoped post-processing transforms. */
  transforms?: ProfileId[]
}

export type GetSysProxyResponse = {
  enable: boolean
  host: string
  port: number
  bypass: string
  server: string
}

/**  ### `verge.yaml` schema */
export type IVerge = IVerge_Serialize | IVerge_Deserialize

/**  ### `verge.yaml` schema */
export type IVerge_Deserialize =
  | ({
      /**  app listening port for app singleton */
      app_singleton_port: number | null
      /**
       *  app log level
       *  silent | error | warn | info | debug | trace
       */
      app_log_level: LoggingLevel_Deserialize | null
      language: string | null
      /**  `light` or `dark` or `system` */
      theme_mode: string | null
      /**  enable traffic graph default is true */
      traffic_graph: boolean | null
      /**  show memory info (only for Clash Meta) */
      enable_memory_usage: boolean | null
      /**  global ui framer motion effects */
      lighten_animation_effects: boolean | null
      /**  clash tun mode */
      enable_tun_mode: boolean | null
      /**  windows service mode */
      enable_service_mode: boolean | null
      /**  can the app auto startup */
      enable_auto_launch: boolean | null
      /**  not show the window on launch */
      enable_silent_start: boolean | null
      /**  set system proxy */
      enable_system_proxy: boolean | null
      /**  enable proxy guard */
      enable_proxy_guard: boolean | null
      /**  set system proxy bypass */
      system_proxy_bypass: string | null
      /**  theme setting */
      theme_color: string | null
      /**  web ui list */
      web_ui_list: string[] | null
      /**  clash core path */
      clash_core: ClashCore_Deserialize | null
      /**
       *  hotkey map
       *  format: {func},{key}
       */
      hotkeys: string[] | null
      /**
       *  切换代理时自动关闭连接 (已弃用)
       * @deprecated use `break_when_proxy_change` instead
       */
      auto_close_connection: boolean | null
      /**
       *  切换代理时中断连接
       *  None: 不中断
       *  Chain: 仅中断使用该代理链的连接
       *  All: 中断所有连接
       */
      break_when_proxy_change: BreakWhenProxyChange | null
      /**
       *  切换配置时中断连接
       *  true: 中断所有连接
       *  false: 不中断连接
       */
      break_when_profile_change: boolean | null
      /**
       *  切换模式时中断连接
       *  true: 中断所有连接
       *  false: 不中断连接
       */
      break_when_mode_change: boolean | null
      /**  默认的延迟测试连接 */
      default_latency_test: string | null
      /**  支持关闭字段过滤，避免meta的新字段都被过滤掉，默认为真 */
      enable_clash_fields: boolean | null
      /**  是否使用内部的脚本支持，默认为真 */
      enable_builtin_enhanced: boolean | null
      /**  proxy 页面布局 列数 */
      proxy_layout_column: number | null
      /**
       *  日志清理
       *  分钟数； 0 为不清理
       * @deprecated use `max_log_files` instead
       */
      auto_log_clean: number | null
      /**  日记轮转时间，单位：天 */
      max_log_files: number | null
      /**
       *  window size and position
       * @deprecated use `window_size_state` instead
       */
      window_size_position: (number | null)[] | null
      window_size_state: WindowState | null
      /**  是否启用随机端口 */
      enable_random_port: boolean | null
      /**  verge mixed port 用于覆盖 clash 的 mixed port */
      verge_mixed_port: number | null
      /**  Check update when app launch */
      enable_auto_check_update: boolean | null
      /**  Clash 相关策略 */
      clash_strategy: ClashStrategy | null
      /**  是否启用代理托盘选择 */
      clash_tray_selector: ProxiesSelectorMode | null
      always_on_top: boolean | null
      /**
       *  Tun 堆栈选择
       *  TODO: 弃用此字段，转移到 clash config 里
       */
      tun_stack: TunStack | null
      /**  是否启用网络统计信息浮窗 */
      network_statistic_widget: NetworkStatisticWidgetConfig | null
      /**
       *  PAC URL for automatic proxy configuration
       *  This field is used to set PAC proxy without exposing it to the frontend UI
       */
      pac_url: string | null
      /**
       *  enable tray text display on Linux systems
       *  When enabled, shows proxy and TUN mode status as text next to the tray icon
       *  When disabled, only shows status via icon changes (prevents text display issues on Wayland)
       */
      enable_tray_text: boolean | null
      /**
       *  Window type to use when opening the app window
       *  Main: opens new main window
       */
      window_type: WindowType | null
      /**
       *  Tray menu implementation mode
       *  Native: use the OS system tray menu (default on non-Windows)
       *  Webview: use a custom WebView window (default on Windows)
       */
      tray_menu_mode: TrayMenuMode | null
      /**
       *  Webview tray menu window dismiss behavior
       *  Hide: hide the window on close (fast re-open, higher memory usage)
       *  Close: destroy the window on close (slower re-open, lower memory usage)
       */
      tray_menu_close_behavior: TrayMenuCloseBehavior | null
    } & {
      /**  proxy guard interval */
      proxy_guard_interval: number | null
    })
  | {
      /**  proxy guard interval */
      proxy_guard_duration: number | null
    }

/**  ### `verge.yaml` schema */
export type IVerge_Serialize = {
  /**  app listening port for app singleton */
  app_singleton_port: number | null
  /**
   *  app log level
   *  silent | error | warn | info | debug | trace
   */
  app_log_level: LoggingLevel_Serialize | null
  language: string | null
  /**  `light` or `dark` or `system` */
  theme_mode: string | null
  /**  enable traffic graph default is true */
  traffic_graph: boolean | null
  /**  show memory info (only for Clash Meta) */
  enable_memory_usage: boolean | null
  /**  global ui framer motion effects */
  lighten_animation_effects: boolean | null
  /**  clash tun mode */
  enable_tun_mode: boolean | null
  /**  windows service mode */
  enable_service_mode?: boolean | null
  /**  can the app auto startup */
  enable_auto_launch: boolean | null
  /**  not show the window on launch */
  enable_silent_start: boolean | null
  /**  set system proxy */
  enable_system_proxy: boolean | null
  /**  enable proxy guard */
  enable_proxy_guard: boolean | null
  /**  set system proxy bypass */
  system_proxy_bypass: string | null
  /**  proxy guard interval */
  proxy_guard_interval: number | null
  /**  theme setting */
  theme_color: string | null
  /**  web ui list */
  web_ui_list: string[] | null
  /**  clash core path */
  clash_core?: ClashCore_Serialize | null
  /**
   *  hotkey map
   *  format: {func},{key}
   */
  hotkeys: string[] | null
  /**
   *  切换代理时自动关闭连接 (已弃用)
   * @deprecated use `break_when_proxy_change` instead
   */
  auto_close_connection: boolean | null
  /**
   *  切换代理时中断连接
   *  None: 不中断
   *  Chain: 仅中断使用该代理链的连接
   *  All: 中断所有连接
   */
  break_when_proxy_change: BreakWhenProxyChange | null
  /**
   *  切换配置时中断连接
   *  true: 中断所有连接
   *  false: 不中断连接
   */
  break_when_profile_change: boolean | null
  /**
   *  切换模式时中断连接
   *  true: 中断所有连接
   *  false: 不中断连接
   */
  break_when_mode_change: boolean | null
  /**  默认的延迟测试连接 */
  default_latency_test: string | null
  /**  支持关闭字段过滤，避免meta的新字段都被过滤掉，默认为真 */
  enable_clash_fields: boolean | null
  /**  是否使用内部的脚本支持，默认为真 */
  enable_builtin_enhanced: boolean | null
  /**  proxy 页面布局 列数 */
  proxy_layout_column: number | null
  /**
   *  日志清理
   *  分钟数； 0 为不清理
   * @deprecated use `max_log_files` instead
   */
  auto_log_clean: number | null
  /**  日记轮转时间，单位：天 */
  max_log_files: number | null
  /**
   *  window size and position
   * @deprecated use `window_size_state` instead
   */
  window_size_position?: (number | null)[] | null
  window_size_state?: WindowState | null
  /**  是否启用随机端口 */
  enable_random_port: boolean | null
  /**  verge mixed port 用于覆盖 clash 的 mixed port */
  verge_mixed_port: number | null
  /**  Check update when app launch */
  enable_auto_check_update: boolean | null
  /**  Clash 相关策略 */
  clash_strategy: ClashStrategy | null
  /**  是否启用代理托盘选择 */
  clash_tray_selector: ProxiesSelectorMode | null
  always_on_top: boolean | null
  /**
   *  Tun 堆栈选择
   *  TODO: 弃用此字段，转移到 clash config 里
   */
  tun_stack: TunStack | null
  /**  是否启用网络统计信息浮窗 */
  network_statistic_widget?: NetworkStatisticWidgetConfig | null
  /**
   *  PAC URL for automatic proxy configuration
   *  This field is used to set PAC proxy without exposing it to the frontend UI
   */
  pac_url?: string | null
  /**
   *  enable tray text display on Linux systems
   *  When enabled, shows proxy and TUN mode status as text next to the tray icon
   *  When disabled, only shows status via icon changes (prevents text display issues on Wayland)
   */
  enable_tray_text: boolean | null
  /**
   *  Window type to use when opening the app window
   *  Main: opens new main window
   */
  window_type: WindowType | null
  /**
   *  Tray menu implementation mode
   *  Native: use the OS system tray menu (default on non-Windows)
   *  Webview: use a custom WebView window (default on Windows)
   */
  tray_menu_mode: TrayMenuMode | null
  /**
   *  Webview tray menu window dismiss behavior
   *  Hide: hide the window on close (fast re-open, higher memory usage)
   *  Close: destroy the window on close (slower re-open, lower memory usage)
   */
  tray_menu_close_behavior: TrayMenuCloseBehavior | null
}

export type LocalBinding = LocalBinding_Serialize | LocalBinding_Deserialize

export type LocalBinding_Deserialize =
  | ({
      type: 'managed'
      file: ManagedProfilePath
      updated_at?: number | null
    } & { mode?: never; target?: never })
  | {
      type: 'external'
      file: ManagedProfilePath
      updated_at?: number | null
      target: ExternalProfilePath
      mode: ExternalMode
    }

export type LocalBinding_Serialize =
  | ({
      type: 'managed'
      file: ManagedProfilePath
      updated_at?: number | null
    } & { mode?: never; target?: never })
  | {
      type: 'external'
      file: ManagedProfilePath
      updated_at?: number | null
      target: ExternalProfilePath
      mode: ExternalMode
    }

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream; the service's own logs are not streamed at all.
 *
 *  TODO: that restriction is the open question here, not a settled posture. A
 *  user-level GUI reading the archive would need one of: a widened DACL (which
 *  means teaching `nyanpasu_utils::io::atomic_fs`'s hardener *and* its verifier
 *  a second acceptable shape — the verifier rejects user-readable DACLs today,
 *  so both move together or directory creation starts failing), some other
 *  grant mechanism, or an RPC that serves the archive so the directory stays
 *  closed. All three are acceptable; none is chosen yet. The two sites that
 *  would change are `log_sink::prepare_dir` and the service's own log directory
 *  setup.
 */
export type LogPathsInfo = LogPathsInfo_Serialize | LogPathsInfo_Deserialize

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream; the service's own logs are not streamed at all.
 *
 *  TODO: that restriction is the open question here, not a settled posture. A
 *  user-level GUI reading the archive would need one of: a widened DACL (which
 *  means teaching `nyanpasu_utils::io::atomic_fs`'s hardener *and* its verifier
 *  a second acceptable shape — the verifier rejects user-readable DACLs today,
 *  so both move together or directory creation starts failing), some other
 *  grant mechanism, or an RPC that serves the archive so the directory stays
 *  closed. All three are acceptable; none is chosen yet. The two sites that
 *  would change are `log_sink::prepare_dir` and the service's own log directory
 *  setup.
 */
export type LogPathsInfo_Deserialize = {
  /**
   *  The service's own logs: JSON lines from `tracing-appender`, rotated
   *  daily, seven files kept.
   */
  service_dir: string
  /**
   *  The core log archive: one rolling JSONL stream, rotated by size and
   *  retained by count. Absent when the manager's sink is switched off, in
   *  which case no such directory exists at all.
   */
  core_dir?: string | null
}

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream; the service's own logs are not streamed at all.
 *
 *  TODO: that restriction is the open question here, not a settled posture. A
 *  user-level GUI reading the archive would need one of: a widened DACL (which
 *  means teaching `nyanpasu_utils::io::atomic_fs`'s hardener *and* its verifier
 *  a second acceptable shape — the verifier rejects user-readable DACLs today,
 *  so both move together or directory creation starts failing), some other
 *  grant mechanism, or an RPC that serves the archive so the directory stays
 *  closed. All three are acceptable; none is chosen yet. The two sites that
 *  would change are `log_sink::prepare_dir` and the service's own log directory
 *  setup.
 */
export type LogPathsInfo_Serialize = {
  /**
   *  The service's own logs: JSON lines from `tracing-appender`, rotated
   *  daily, seven files kept.
   */
  service_dir: string
  /**
   *  The core log archive: one rolling JSONL stream, rotated by size and
   *  retained by count. Absent when the manager's sink is switched off, in
   *  which case no such directory exists at all.
   */
  core_dir?: string | null
}

export type LogSpan = 'log' | 'info' | 'warn' | 'error'

export type LoggingLevel = LoggingLevel_Serialize | LoggingLevel_Deserialize

export type LoggingLevel_Deserialize =
  | 'silent'
  | 'off'
  | 'trace'
  | 'tracing'
  | 'debug'
  | 'info'
  | 'warn'
  | 'warning'
  | 'error'

export type LoggingLevel_Serialize =
  | 'silent'
  | 'trace'
  | 'debug'
  | 'info'
  | 'warn'
  | 'error'

/**  A path relative to the application-managed profile directory. */
export type ManagedProfilePath = string

export type ManifestVersionLatest = {
  mihomo: string
  mihomo_alpha: string
  clash_rs: string
  clash_rs_alpha: string
  clash_premium: string
  meow: string
}

/**  Stable read location used by parsers and processors. */
export type MaterializedFile =
  | MaterializedFile_Serialize
  | MaterializedFile_Deserialize

/**  Stable read location used by parsers and processors. */
export type MaterializedFile_Deserialize = {
  file: ManagedProfilePath
  /**  Last successful materialization time. */
  updated_at?: number | null
}

/**  Stable read location used by parsers and processors. */
export type MaterializedFile_Serialize = {
  file: ManagedProfilePath
  /**  Last successful materialization time. */
  updated_at?: number | null
}

/**
 *  Public mutation wire (PR-4S S08 / plan §12): state is committed first; post-
 *  commit side-effect failures degrade instead of erroring.
 *
 *  Final wire is only `applied` / `committed_degraded` — no `_v1` alias.
 */
export type MutationOutcome<T> =
  | { status: 'applied'; value: T }
  | { status: 'committed_degraded'; value: T; degradations: Degradation[] }

export type NetworkStatisticWidgetConfig = 'disabled' | 'large' | 'small'

export type NewProfileRequest =
  | NewProfileRequest_Serialize
  | NewProfileRequest_Deserialize

export type NewProfileRequest_Deserialize = {
  metadata: ProfileMetadata_Deserialize
  /**  Add rewrites the materialized path to `{uid}.{ext}`. */
  definition: ProfileDefinition_Deserialize
}

export type NewProfileRequest_Serialize = {
  metadata: ProfileMetadata_Serialize
  /**  Add rewrites the materialized path to `{uid}.{ext}`. */
  definition: ProfileDefinition_Serialize
}

export type OverlayTransform =
  | OverlayTransform_Serialize
  | OverlayTransform_Deserialize

export type OverlayTransform_Deserialize = {
  source: ProfileSource_Deserialize
}

export type OverlayTransform_Serialize = {
  source: ProfileSource_Serialize
}

export type PatchRuntimeConfig =
  | PatchRuntimeConfig_Serialize
  | PatchRuntimeConfig_Deserialize

export type PatchRuntimeConfig_Deserialize = {
  'allow-lan'?: boolean | null
  ipv6?: boolean | null
  'log-level'?: string | null
  mode?: string | null
}

export type PatchRuntimeConfig_Serialize = {
  'allow-lan'?: boolean | null
  ipv6?: boolean | null
  'log-level'?: string | null
  mode?: string | null
}

/**  后处理输出 */
export type PostProcessingOutput = {
  /**  局部链的输出 */
  scopes: { [key in string]: { [key in string]: [LogSpan, string][] } }
  /**  全局链的输出 */
  global: { [key in string]: [LogSpan, string][] }
  /**  根据配置进行的分析建议 */
  advice: [LogSpan, string][]
}

/**  Top-level semantic split. */
export type ProfileDefinition =
  | ProfileDefinition_Serialize
  | ProfileDefinition_Deserialize

/**  Top-level semantic split. */
export type ProfileDefinition_Deserialize =
  | ({ type: 'config'; config: ConfigDefinition_Deserialize } & {
      transform?: never
    })
  | ({ type: 'transform'; transform: TransformDefinition_Deserialize } & {
      config?: never
    })

/**  Top-level semantic split. */
export type ProfileDefinition_Serialize =
  | ({ type: 'config'; config: ConfigDefinition_Serialize } & {
      transform?: never
    })
  | ({ type: 'transform'; transform: TransformDefinition_Serialize } & {
      config?: never
    })

export type ProfileDocument =
  | ProfileDocument_Serialize
  | ProfileDocument_Deserialize

export type ProfileDocument_Deserialize = {
  current?: ProfileId | null
  global_transforms?: ProfileId[]
  valid: string[]
  items: ProfileItem_Deserialize[]
}

export type ProfileDocument_Serialize = {
  current?: ProfileId | null
  global_transforms?: ProfileId[]
  valid: string[]
  items: ProfileItem_Serialize[]
}

/**  Stable profile identifier. It is also the key used by [`Profiles::items`]. */
export type ProfileId = string

/**  One named profile item. */
export type ProfileItem = ProfileItem_Serialize | ProfileItem_Deserialize

/**  One named profile item. */
export type ProfileItem_Deserialize = {
  uid: ProfileId
} & ProfileMetadata_Deserialize &
  ProfileDefinition_Deserialize

/**  One named profile item. */
export type ProfileItem_Serialize = {
  uid: ProfileId
} & ProfileMetadata_Serialize &
  ProfileDefinition_Serialize

/**  Public, user-editable profile metadata. */
export type ProfileMetadata =
  | ProfileMetadata_Serialize
  | ProfileMetadata_Deserialize

export type ProfileMetadataPatch =
  | ProfileMetadataPatch_Serialize
  | ProfileMetadataPatch_Deserialize

export type ProfileMetadataPatch_Deserialize = {
  name: string | null
  desc?: string | null
  custom_name?: boolean | null
}

export type ProfileMetadataPatch_Serialize = {
  name?: string | null
  desc?: string | null
  custom_name?: boolean | null
}

/**  Public, user-editable profile metadata. */
export type ProfileMetadata_Deserialize = {
  name: string
  desc?: string | null
  /**
   *  Provenance flag: `true` when the name was chosen by the user (manual
   *  create or rename) and must not be overwritten by subscription name-sync.
   *  Profiles persisted before this field predate provenance tracking; absence
   *  means user-owned so a refresh cannot silently rename them.
   *  The value is never trusted from an incoming patch — it is set only by
   *  rename detection and name-sync (see `ProfileItem::apply_metadata_patch`).
   *  Only the non-default `false` (an unpinned, sync-eligible profile) is
   *  persisted; a user-owned `true` is left off the wire and restored by the
   *  default, so legacy and user-named documents stay byte-identical.
   */
  custom_name?: boolean
}

/**  Public, user-editable profile metadata. */
export type ProfileMetadata_Serialize = {
  name: string
  desc?: string | null
  /**
   *  Provenance flag: `true` when the name was chosen by the user (manual
   *  create or rename) and must not be overwritten by subscription name-sync.
   *  Profiles persisted before this field predate provenance tracking; absence
   *  means user-owned so a refresh cannot silently rename them.
   *  The value is never trusted from an incoming patch — it is set only by
   *  rename detection and name-sync (see `ProfileItem::apply_metadata_patch`).
   *  Only the non-default `false` (an unpinned, sync-eligible profile) is
   *  persisted; a user-owned `true` is left off the wire and restored by the
   *  default, so legacy and user-named documents stay byte-identical.
   */
  custom_name?: boolean
}

export type ProfileRemoteOptions = {
  user_agent?: string | null
  with_proxy: boolean
  self_proxy: boolean
  update_interval_minutes: number
}

/**
 *  Who is responsible for maintaining the locally readable file.
 *
 *  `Remote + External` is unrepresentable: external binding exists only inside
 *  the `Local` branch, while `Remote` owns a managed materialization directly.
 */
export type ProfileSource = ProfileSource_Serialize | ProfileSource_Deserialize

/**
 *  Who is responsible for maintaining the locally readable file.
 *
 *  `Remote + External` is unrepresentable: external binding exists only inside
 *  the `Local` branch, while `Remote` owns a managed materialization directly.
 */
export type ProfileSource_Deserialize =
  | ({ type: 'local'; binding: LocalBinding_Deserialize } & {
      file?: never
      option?: never
      subscription?: never
      updated_at?: never
      url?: never
    })
  | ({
      type: 'remote'
      file: ManagedProfilePath
      updated_at?: number | null
      url: string
      option?: ProfileRemoteOptions
      subscription?: ProfileSubscriptionInfo
    } & { binding?: never })

/**
 *  Who is responsible for maintaining the locally readable file.
 *
 *  `Remote + External` is unrepresentable: external binding exists only inside
 *  the `Local` branch, while `Remote` owns a managed materialization directly.
 */
export type ProfileSource_Serialize =
  | ({ type: 'local'; binding: LocalBinding_Serialize } & {
      file?: never
      option?: never
      subscription?: never
      updated_at?: never
      url?: never
    })
  | ({
      type: 'remote'
      file: ManagedProfilePath
      updated_at?: number | null
      url: string
      option: ProfileRemoteOptions
      subscription?: ProfileSubscriptionInfo
    } & { binding?: never })

export type ProfileSubscriptionInfo = {
  upload?: number | null
  download?: number | null
  total?: number | null
  expire?: number | null
}

export type ProfileValidationError =
  | ({
      ItemKeyMismatch: {
        key: ProfileId
        item_uid: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({ CurrentNotFound: ProfileId } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({ CurrentNotConfig: ProfileId } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      TransformTargetNotFound: {
        owner: TransformOwner
        target: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      TransformTargetNotTransform: {
        owner: TransformOwner
        target: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      EmptyCompositionConfig: {
        composition: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionSelfReference: {
        composition: ProfileId
        role: CompositionMemberRole
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionMemberNotFound: {
        composition: ProfileId
        role: CompositionMemberRole
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionMemberNotDirectFileConfig: {
        composition: ProfileId
        role: CompositionMemberRole
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionBaseAlsoContributor: {
        composition: ProfileId
        profile: ProfileId
      }
    } & {
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionDuplicateContributor: {
        composition: ProfileId
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      DuplicateMaterializedFile: {
        file: ManagedProfilePath
        first: ProfileId
        second: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      UnsupportedRemoteUrlScheme: {
        profile: ProfileId
        scheme: string
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
    })
  | ({
      RemoteUpdateIntervalIsZero: {
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })

export type ProviderType = 'Proxy' | 'Rule' | 'Unknown'

export type ProvidersProxiesRes =
  | ProvidersProxiesRes_Serialize
  | ProvidersProxiesRes_Deserialize

export type ProvidersProxiesRes_Deserialize = {
  providers?: { [key in string]: ProxyProviderItem_Deserialize }
}

export type ProvidersProxiesRes_Serialize = {
  providers: { [key in string]: ProxyProviderItem_Serialize }
}

export type ProvidersRulesRes = {
  providers: { [key in string]: RuleProviderItem }
}

export type Proxies = Proxies_Serialize | Proxies_Deserialize

export type ProxiesSelectorMode = 'hidden' | 'normal' | 'submenu'

export type Proxies_Deserialize = {
  global: ProxyGroupItem_Deserialize
  direct: ProxyItem_Deserialize
  groups: ProxyGroupItem_Deserialize[]
  records: { [key in string]: ProxyItem_Deserialize }
  proxies: ProxyItem_Deserialize[]
}

export type Proxies_Serialize = {
  global: ProxyGroupItem_Serialize
  direct: ProxyItem_Serialize
  groups: ProxyGroupItem_Serialize[]
  records: { [key in string]: ProxyItem_Serialize }
  proxies: ProxyItem_Serialize[]
}

export type ProxyGroupItem =
  | ProxyGroupItem_Serialize
  | ProxyGroupItem_Deserialize

export type ProxyGroupItem_Deserialize = {
  name: string
  type: string
  udp: boolean
  history: ProxyItemHistory[]
  all: ProxyItem_Deserialize[]
  now: string | null
  provider: string | null
  alive: boolean | null
  xudp: boolean | null
  tfo: boolean | null
  icon: string | null
  hidden?: boolean
}

export type ProxyGroupItem_Serialize = {
  name: string
  type: string
  udp: boolean
  history: ProxyItemHistory[]
  all: ProxyItem_Serialize[]
  now: string | null
  provider: string | null
  alive: boolean | null
  xudp?: boolean | null
  tfo?: boolean | null
  icon?: string | null
  hidden: boolean
}

export type ProxyItem = ProxyItem_Serialize | ProxyItem_Deserialize

export type ProxyItemHistory = {
  time: string
  delay: number
}

export type ProxyItem_Deserialize = {
  name: string
  type: string
  udp: boolean
  history: ProxyItemHistory[]
  all: string[] | null
  now: string | null
  provider: string | null
  alive: boolean | null
  xudp: boolean | null
  tfo: boolean | null
  icon: string | null
  hidden?: boolean
}

export type ProxyItem_Serialize = {
  name: string
  type: string
  udp: boolean
  history: ProxyItemHistory[]
  all: string[] | null
  now: string | null
  provider: string | null
  alive: boolean | null
  xudp?: boolean | null
  tfo?: boolean | null
  icon?: string | null
  hidden: boolean
}

export type ProxyProviderItem =
  | ProxyProviderItem_Serialize
  | ProxyProviderItem_Deserialize

export type ProxyProviderItem_Deserialize = {
  name: string
  type: ProviderType
  proxies: ProxyItem_Deserialize[]
  vehicleType: VehicleType
  updatedAt: string | null
  subscriptionInfo: SubscriptionInfo_Deserialize | null
  testUrl: string | null
  expectedStatus: string | null
}

export type ProxyProviderItem_Serialize = {
  name: string
  type: ProviderType
  proxies: ProxyItem_Serialize[]
  vehicleType: VehicleType
  updatedAt?: string | null
  subscriptionInfo?: SubscriptionInfo_Serialize | null
  testUrl?: string | null
  expectedStatus?: string | null
}

export type RemoteProfileOptionsPatch =
  | RemoteProfileOptionsPatch_Serialize
  | RemoteProfileOptionsPatch_Deserialize

export type RemoteProfileOptionsPatch_Deserialize = {
  user_agent?: string | null
  with_proxy: boolean | null
  self_proxy: boolean | null
  update_interval_minutes: number | null
}

export type RemoteProfileOptionsPatch_Serialize = {
  user_agent?: string | null
  with_proxy?: boolean | null
  self_proxy?: boolean | null
  update_interval_minutes?: number | null
}

/**
 *  The compare-and-swap identity of a config revision.
 *
 *  Deliberately a subset of [`ConfigRevisionInfo`]: the manager's CAS compares
 *  epoch, generation and `effective_hash` only, so carrying `source_hash` here
 *  would imply it takes part.
 */
export type RevisionIdInfo = {
  epoch: number
  generation: number
  effective_hash: string
}

export type RuleProviderItem = {
  behavior: string | null
  format: string | null
  name: string
  ruleCount: number | null
  type: string | null
  updatedAt: string | null
  vehicleType: string | null
}

export type RulesRes = {
  rules: ClashRule[]
}

export type RuntimeInfos = {
  service_data_dir: string
  service_config_dir: string
  nyanpasu_config_dir: string
  nyanpasu_data_dir: string
}

/**
 *  Emitted to the frontend when a `clash-nyanpasu`/`clash` custom-scheme deep
 *  link is received: either from a secondary instance while the app is already
 *  running, or on cold start once the window exists. The frontend listens for
 *  this to import the referenced `install-config` profile. On cold start the
 *  same URL is also stashed in [`PendingDeepLink`] and drained once via
 *  [`get_pending_deep_link`], covering the race where the event fires before the
 *  JS listener attaches.
 *
 *  Event name: `scheme-request-received-event` (derived by `tauri_specta`).
 */
export type SchemeRequestReceivedEvent = {
  /**  The raw deep-link URL as received from the OS. */
  url: string
}

export type ScriptRuntime = 'javascript' | 'lua'

export type ScriptTransform =
  | ScriptTransform_Serialize
  | ScriptTransform_Deserialize

export type ScriptTransform_Deserialize = {
  source: ProfileSource_Deserialize
  runtime: ScriptRuntime
}

export type ScriptTransform_Serialize = {
  source: ProfileSource_Serialize
  runtime: ScriptRuntime
}

export type ServiceCompat =
  /**  daemon 未安装 / 未运行 / 未上报 server 信息，没有可判定的版本。 */
  | { kind: 'unknown' }
  /**  主版本匹配，允许进入 Service backend。 */
  | { kind: 'compatible'; server_version: string }
  /**
   *  主版本不匹配（典型：v1.4.5），或主版本对但低于最低版本（典型：
   *  v2.0.0-rc.1）。fail-closed。
   */
  | {
      kind: 'incompatible'
      server_version: string
      required_major: number
      /**
       *  供 UI 展示：只说"需要 v2.x"无法解释一台 major 正确却被拒的
       *  daemon，它装的**就是** v2.x。
       */
      required_min: string
    }
  /**  server 上报的版本不是合法 semver。fail-closed。 */
  | { kind: 'unparsable'; server_version: string }

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus =
  | ServiceHostStatus_Serialize
  | ServiceHostStatus_Deserialize

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus_Deserialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Deserialize | null
  phase: ServicePhase
  compat: ServiceCompat
  restart_attempts: number
}

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus_Serialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Serialize | null
  phase: ServicePhase
  compat: ServiceCompat
  restart_attempts: number
}

export type ServicePhase =
  | 'probing'
  | 'not_installed'
  | 'daemon_stopped'
  | 'installing'
  | 'starting_daemon'
  | 'ready'
  /**  Version gate failed closed: upgrade required, never downgraded to. */
  | 'incompatible'
  | 'restarting'
  /**  Auto-restart budget spent; waits for an explicit `EnsureReady`. */
  | 'exhausted'
  | 'uninstalling'
  /**
   *  The probe itself failed or timed out (F5): what the daemon actually
   *  is cannot be determined. Never treated as `DaemonStopped` -- an
   *  unreachable daemon might still be holding a core open, so callers
   *  that gate on "no core held" (the uninstall guard, `EndpointDown`'s
   *  restart) must refuse rather than proceed.
   */
  | 'unknown'

export type ServiceStatus = 'not_installed' | 'stopped' | 'running'

export type ServiceStatusChangedEvent =
  | ServiceStatusChangedEvent_Serialize
  | ServiceStatusChangedEvent_Deserialize

export type ServiceStatusChangedEvent_Deserialize =
  ServiceHostStatus_Deserialize

export type ServiceStatusChangedEvent_Serialize = ServiceHostStatus_Serialize

/**
 *  `StatusInfo` 的 additive 镜像：字段逐一复制（specta 不支持 `serde(flatten)`，
 *  见本文件 `GetSysProxyResponse` 的同款处理），追加 actor 投影字段。
 *  wire 是原结构的严格超集，前端既有消费点不受影响。
 */
export type ServiceStatusInfo =
  | ServiceStatusInfo_Serialize
  | ServiceStatusInfo_Deserialize

/**
 *  `StatusInfo` 的 additive 镜像：字段逐一复制（specta 不支持 `serde(flatten)`，
 *  见本文件 `GetSysProxyResponse` 的同款处理），追加 actor 投影字段。
 *  wire 是原结构的严格超集，前端既有消费点不受影响。
 */
export type ServiceStatusInfo_Deserialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Deserialize | null
  compat: ServiceCompat
  phase: ServicePhase
  restart_attempts: number
}

/**
 *  `StatusInfo` 的 additive 镜像：字段逐一复制（specta 不支持 `serde(flatten)`，
 *  见本文件 `GetSysProxyResponse` 的同款处理），追加 actor 投影字段。
 *  wire 是原结构的严格超集，前端既有消费点不受影响。
 */
export type ServiceStatusInfo_Serialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Serialize | null
  compat: ServiceCompat
  phase: ServicePhase
  restart_attempts: number
}

export type StatusResBody = StatusResBody_Serialize | StatusResBody_Deserialize

export type StatusResBody_Deserialize = {
  version: string
  core_infos: CoreInfos_Deserialize
  runtime_infos: RuntimeInfos
  /**
   *  Declared last and omitted rather than null when absent, so a payload
   *  without it is byte-identical to the pre-L3 format — the rule S7 used for
   *  `CoreInfos`. The service always sends it; the `Option` exists so every
   *  existing golden literal stays unchanged.
   */
  logs?: LogPathsInfo_Deserialize | null
}

export type StatusResBody_Serialize = {
  version: string
  core_infos: CoreInfos_Serialize
  runtime_infos: RuntimeInfos
  /**
   *  Declared last and omitted rather than null when absent, so a payload
   *  without it is byte-identical to the pre-L3 format — the rule S7 used for
   *  `CoreInfos`. The service always sends it; the `Option` exists so every
   *  existing golden literal stays unchanged.
   */
  logs?: LogPathsInfo_Serialize | null
}

export type StorageEntry = {
  key: string
  /**  Raw JSON-encoded value string. */
  value: string
}

/**
 *  Event emitted to all windows when a storage value changes.
 *  Event name: `storage-value-changed-event`
 */
export type StorageValueChangedEvent = {
  key: string
  /**  The new JSON-encoded value, or `None` if the key was removed. */
  value: string | null
}

export type SubscriptionInfo =
  | SubscriptionInfo_Serialize
  | SubscriptionInfo_Deserialize

export type SubscriptionInfo_Deserialize =
  | {
      upload?: number
    }
  | ({
      Upload?: number
    } & {
      download?: number
    })
  | ({
      Download?: number
    } & {
      total?: number
    })
  | ({
      Total?: number
    } & {
      expire?: number
    })
  | {
      Expire?: number
    }

export type SubscriptionInfo_Serialize = {
  upload: number
  download: number
  total: number
  expire: number
}

/**  A named config transformer. Transform profiles are reusable but not activatable. */
export type TransformDefinition =
  | TransformDefinition_Serialize
  | TransformDefinition_Deserialize

/**  A named config transformer. Transform profiles are reusable but not activatable. */
export type TransformDefinition_Deserialize =
  /**  Declarative YAML overlay/patch. This is the new name for legacy Merge. */
  | ({ type: 'overlay'; source: ProfileSource_Deserialize } & {
      runtime?: never
    })
  /**  Imperative JS/Lua transform. */
  | {
      type: 'script'
      source: ProfileSource_Deserialize
      runtime: ScriptRuntime
    }

/**  A named config transformer. Transform profiles are reusable but not activatable. */
export type TransformDefinition_Serialize =
  /**  Declarative YAML overlay/patch. This is the new name for legacy Merge. */
  | ({ type: 'overlay'; source: ProfileSource_Serialize } & { runtime?: never })
  /**  Imperative JS/Lua transform. */
  | { type: 'script'; source: ProfileSource_Serialize; runtime: ScriptRuntime }

export type TransformOwner =
  | { type: 'global' }
  | { type: 'config'; uid: ProfileId }

export type TrayIcon = 'normal' | 'tun' | 'system_proxy'

export type TrayMenuCloseBehavior = 'hide' | 'close'

export type TrayMenuMode = 'native' | 'webview'

export type TunStack = 'system' | 'gvisor' | 'mixed'

export type UpdateWrapper = {
  rid: number
  available: boolean
  current_version: string
  version: string
  date: string | null
  body: string | null
  raw_json: any
}

export type UpdaterState =
  | 'idle'
  | 'downloading'
  | 'decompressing'
  | 'replacing'
  | 'restarting'
  | 'done'
  | { failed: string }

export type UpdaterSummary = {
  id: number
  state: UpdaterState
  downloader: DownloadStatus
}

export type VehicleType = 'File' | 'HTTP' | 'Compatible' | 'Unknown'

/**  Message for inter-window communication */
export type WindowMessageEvent = {
  /**  Source window label */
  from: string
  /**  Target window label (use "*" for broadcast) */
  to: string
  /**  Message type/event name */
  event: string
  /**  Message payload */
  payload: any
}

/**
 *  Event emitted by the frontend when a window's webview is ready and visible.
 *  Carries the window label so the backend can handle per-window logic.
 *  Event name: `window-ready-event`
 */
export type WindowReadyEvent = {
  label: string
}

export type WindowState = {
  width: number
  height: number
  x: number
  y: number
  maximized: boolean
  fullscreen: boolean
}

export type WindowType = 'main'

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}

type EventEmit<T> = [T] extends [null]
  ? () => Promise<void>
  : (payload: T) => Promise<void>

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent =
    (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
      cb({
        ...event,
        payload: deserialize ? deserialize(event.payload) : event.payload,
      })
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload)

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  }

  const fn = (
    target:
      | import('@tauri-apps/api/webview').Webview
      | import('@tauri-apps/api/window').Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  })

  return Object.assign(fn, base)
}
