/* oxlint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core'
import * as __TAURI_EVENT from '@tauri-apps/api/event'

/** Commands */
export const commands = {
  callRpc: (method: string, params: RpcValue) =>
    typedError<RpcValue, RpcError>(
      __TAURI_INVOKE('call_rpc', { method, params }),
    ),
  subscribeClashConnectionDetails: (
    onFrame: Channel<ClashConnectionDetails_Deserialize>,
  ) =>
    typedError<SubscriptionId, IpcError>(
      __TAURI_INVOKE('subscribe_clash_connection_details', { onFrame }),
    ),
  unsubscribeClashConnectionDetails: (id: SubscriptionId) =>
    typedError<null, IpcError>(
      __TAURI_INVOKE('unsubscribe_clash_connection_details', { id }),
    ),
}

/** Events */
export const events = {
  clashWsEvent: makeEvent<ClashWsEvent>('clash-ws-event'),
  configurationStatusChanged: makeEvent<ConfigurationStatusChanged>(
    'configuration-status-changed',
  ),
  coreStatusChangedEvent: makeEvent<CoreStatusChangedEvent>(
    'core-status-changed-event',
  ),
  schemeRequestReceivedEvent: makeEvent<SchemeRequestReceivedEvent>(
    'scheme-request-received-event',
  ),
  serviceStatusChangedEvent: makeEvent<ServiceStatusChangedEvent_Deserialize>(
    'service-status-changed-event',
  ),
  storageValueChangedEvent: makeEvent<StorageValueChangedEvent>(
    'storage-value-changed-event',
  ),
  windowMessageEvent: makeEvent<WindowMessageEvent>('window-message-event'),
  windowReadyEvent: makeEvent<WindowReadyEvent>('window-ready-event'),
}

/* Types */
/**  Built-in post-processing steps applied to the selected config. */
export type BuiltinStepKind =
  | 'guard_overrides'
  | 'whitelist_field_filter'
  | 'include_all_expansion'
  | 'finalizing'
  | 'core_controller'

/**
 *  One connection plus its derived rates, for IPC consumers that need the
 *  per-connection detail (only built when `with_details` is set).
 */
export type ClashConnection =
  ClashConnection_Serialize | ClashConnection_Deserialize

/**
 *  Latest per-connection detail frame, pushed only while at least one
 *  subscriber exists (see `StreamsClient::subscribe_connection_details`);
 *  only the newest frame is kept, never a history.
 */
export type ClashConnectionDetails =
  ClashConnectionDetails_Serialize | ClashConnectionDetails_Deserialize

/**
 *  Latest per-connection detail frame, pushed only while at least one
 *  subscriber exists (see `StreamsClient::subscribe_connection_details`);
 *  only the newest frame is kept, never a history.
 */
export type ClashConnectionDetails_Deserialize = {
  /**
   *  Equal to the sequence of the `ConnectionsUpdated` event emitted for
   *  the same sample, so a subscriber can align the two.
   */
  sequence: number
  connections: ClashConnection_Deserialize[]
}

/**
 *  Latest per-connection detail frame, pushed only while at least one
 *  subscriber exists (see `StreamsClient::subscribe_connection_details`);
 *  only the newest frame is kept, never a history.
 */
export type ClashConnectionDetails_Serialize = {
  /**
   *  Equal to the sequence of the `ConnectionsUpdated` event emitted for
   *  the same sample, so a subscriber can align the two.
   */
  sequence: number
  connections: ClashConnection_Serialize[]
}

/**
 *  One connection plus its derived rates, for IPC consumers that need the
 *  per-connection detail (only built when `with_details` is set).
 */
export type ClashConnection_Deserialize = {
  downloadSpeed: number
  uploadSpeed: number
} & Connection_Deserialize

/**
 *  One connection plus its derived rates, for IPC consumers that need the
 *  per-connection detail (only built when `with_details` is set).
 */
export type ClashConnection_Serialize = {
  downloadSpeed: number
  uploadSpeed: number
} & Connection_Serialize

export type ClashConnectionsConnectorState =
  'disconnected' | 'connecting' | 'connected'

/**  Pushed on every connection sample; size is independent of connection count. */
export type ClashConnectionsSummary = {
  downloadTotal: number
  uploadTotal: number
  downloadSpeed: number
  uploadSpeed: number
  memory: number | null
  connectionCount: number
  /**
   *  Keyed by chain member name (group or node); summed over every
   *  connection whose `chains` contains that name.
   */
  memberRates: { [key in string]: TrafficRate }
}

export type ClashCoreType =
  'mihomo' | 'mihomo-alpha' | 'clash-rs' | 'clash-rs-alpha' | 'clash' | 'meow'

export type ClashWsEvent = {
  sequence: number
  update: ClashWsUpdate
}

export type ClashWsKind = 'connections' | 'logs' | 'traffic' | 'memory'

export type ClashWsLog = {
  type: string
  time: string | null
  payload: string
}

export type ClashWsMemory = {
  inuse: number
  oslimit: number
}

export type ClashWsRecording = {
  connections: boolean
  logs: boolean
  traffic: boolean
  memory: boolean
}

export type ClashWsSnapshot = {
  sequence: number
  state: ClashConnectionsConnectorState
  recording: ClashWsRecording
  connections: ClashConnectionsSummary[]
  logs: ClashWsLog[]
  traffic: ClashWsTraffic[]
  memory: ClashWsMemory[]
}

export type ClashWsTraffic = {
  up: number
  down: number
}

export type ClashWsUpdate =
  | { kind: 'reset'; data: ClashWsSnapshot }
  | { kind: 'state_changed'; data: ClashConnectionsConnectorState }
  | { kind: 'connections_updated'; data: ClashConnectionsSummary }
  | { kind: 'log_appended'; data: ClashWsLog }
  | { kind: 'traffic_updated'; data: ClashWsTraffic }
  | { kind: 'memory_updated'; data: ClashWsMemory }
  | { kind: 'recording_changed'; data: ClashWsRecording }
  | { kind: 'history_cleared'; data: ClashWsKind }

/**
 *  Why a source transaction did not commit, classified once from the
 *  persistence error and, when the Runtime took part, the receipt it settled
 *  (U7). A source wraps it in its own domain error.
 */
export type CommitAborted =
  /**  The yaml write failed; nothing committed. */
  | { kind: 'write_config'; runtime: RuntimeAftermath }
  /**  The write failed and so did the recovery of what the transaction staged. */
  | { kind: 'recover_after_write_failure'; runtime: RuntimeAftermath }
  /**  A required participant refused the candidate. */
  | {
      kind: 'runtime_refused'
      errors: RuntimeError[]
      runtime: RuntimeAftermath
    }
  /**  A required participant could not decide. */
  | {
      kind: 'runtime_failed'
      errors: RuntimeError[]
      runtime: RuntimeAftermath
    }
  /**
   *  The coordinator refused before persisting: builder validation, or a CAS
   *  mismatch the caller did not classify as its own version conflict.
   */
  | { kind: 'validate_state' }

export type CompositionMemberRole = 'base' | 'contributor'

/**  Which source domain a mutation belongs to. */
export type ConfigDomain = 'application' | 'clash' | 'profiles'

/**  Open response value; mutation and subscription enums remain closed. */
export type ConfigEnum<T> = T | string

export type ConfigError =
  /**  A nightly build keeps its channel. */
  | { kind: 'leave_nightly_channel'; to: ReleaseChannel }
  | { kind: 'invalid_update_sources'; reason: string }
  | { kind: 'validate_hotkeys'; source: HotkeyParseError }
  | { kind: 'workflow_not_ready' }
  | { kind: 'shutting_down'; domain: ConfigDomain }
  /**  The owner's mailbox is closed, or it dropped the reply. */
  | { kind: 'owner_stopped'; domain: ConfigDomain }
  | {
      kind: 'version_conflict'
      domain: ConfigDomain
      expected: number
      actual: number
    }
  | { kind: 'commit'; domain: ConfigDomain; source: CommitAborted }
  | { kind: 'persist_session_state' }
  | { kind: 'session_state_stopped' }

/**  Why a config pipeline is being executed. */
export type ConfigExecutionRole =
  /**  The final config selected by `Profiles.current`. */
  | { kind: 'selected' }
  /**  Built as the base member of a composition. */
  | {
      kind: 'composition_base'
      data: {
        composition_id: ProfileId
      }
    }
  /**  Built as a proxies contributor of a composition. */
  | {
      kind: 'composition_contributor'
      data: {
        composition_id: ProfileId
        contributor_index: number
      }
    }

/**
 *  Identity of the config the running core actually adopted.
 *
 *  `source_hash` is computed over the caller's own file and `effective_hash`
 *  over the canonical form the core is running, both FNV-1a over canonical
 *  YAML. A caller that holds the source file can therefore confirm the
 *  service read the same bytes it wrote, without reimplementing the hash.
 *  The manager's private runtime copy path is deliberately not exposed: it
 *  lives in a 0o700 directory the caller cannot read, so it would only
 *  mislead.
 */
export type ConfigRevisionInfo = {
  epoch: number
  generation: number
  source_hash: string
  effective_hash: string
}

export type ConfigurationStatus = {
  event_seq: number
  maintenance: string | null
  source_versions: SourceVersions
  runtime: RuntimeConvergence
  effects: EffectConvergence[]
  /**  The latest background-source receipt per profile. */
  sources: SourceStatus[]
  active: string | null
  recent_operations: OperationStatus[]
}

export type ConfigurationStatusChanged = ConfigurationStatus

export type Connection = Connection_Serialize | Connection_Deserialize

export type ConnectionMetadata =
  ConnectionMetadata_Serialize | ConnectionMetadata_Deserialize

/**
 *  Known `ConnectionMetadata` fields. Flattened into both [`ConnectionMetadata`]
 *  (serialize) and [`ConnectionMetadataWire`] (deserialize) so they are only
 *  defined once; see [`ConnectionMetadata::extra`] for the unknown-field split.
 */
export type ConnectionMetadataFields =
  ConnectionMetadataFields_Serialize | ConnectionMetadataFields_Deserialize

/**
 *  Known `ConnectionMetadata` fields. Flattened into both [`ConnectionMetadata`]
 *  (serialize) and [`ConnectionMetadataWire`] (deserialize) so they are only
 *  defined once; see [`ConnectionMetadata::extra`] for the unknown-field split.
 */
export type ConnectionMetadataFields_Deserialize = {
  network?: ConfigEnum<ConnectionNetwork> | null
  type?: ConfigEnum<ConnectionType> | null
  sourceIP?: string | null
  destinationIP?: string | null
  sourceGeoIP?: string[] | null
  destinationGeoIP?: string[] | null
  sourceIPASN?: string | null
  destinationIPASN?: string | null
  sourcePort?: string | null
  destinationPort?: string | null
  inboundIP?: string | null
  inboundPort?: string | null
  inboundName?: string | null
  inboundUser?: string | null
  rematchName?: string | null
  host?: string | null
  dnsMode?: ConfigEnum<DnsMode> | null
  uid?: number | null
  process?: string | null
  processPath?: string | null
  specialProxy?: string | null
  specialRules?: string | null
  remoteDestination?: string | null
  dscp?: number | null
  sniffHost?: string | null
}

/**
 *  Known `ConnectionMetadata` fields. Flattened into both [`ConnectionMetadata`]
 *  (serialize) and [`ConnectionMetadataWire`] (deserialize) so they are only
 *  defined once; see [`ConnectionMetadata::extra`] for the unknown-field split.
 */
export type ConnectionMetadataFields_Serialize = {
  network?: ConfigEnum<ConnectionNetwork> | null
  type?: ConfigEnum<ConnectionType> | null
  sourceIP?: string | null
  destinationIP?: string | null
  sourceGeoIP?: string[] | null
  destinationGeoIP?: string[] | null
  sourceIPASN?: string | null
  destinationIPASN?: string | null
  sourcePort?: string | null
  destinationPort?: string | null
  inboundIP?: string | null
  inboundPort?: string | null
  inboundName?: string | null
  inboundUser?: string | null
  rematchName?: string | null
  host?: string | null
  dnsMode?: ConfigEnum<DnsMode> | null
  uid?: number | null
  process?: string | null
  processPath?: string | null
  specialProxy?: string | null
  specialRules?: string | null
  remoteDestination?: string | null
  dscp?: number | null
  sniffHost?: string | null
}

/**  Deserialize-only mirror of [`ConnectionMetadata`]; see [`ConnectionWire`]. */
export type ConnectionMetadataWire =
  ConnectionMetadataWire_Serialize | ConnectionMetadataWire_Deserialize

/**  Deserialize-only mirror of [`ConnectionMetadata`]; see [`ConnectionWire`]. */
export type ConnectionMetadataWire_Deserialize =
  ConnectionMetadataFields_Deserialize & { [key in string]: JsonValue | null }

/**  Deserialize-only mirror of [`ConnectionMetadata`]; see [`ConnectionWire`]. */
export type ConnectionMetadataWire_Serialize =
  ConnectionMetadataFields_Serialize & { [key in string]: JsonValue | null }

export type ConnectionMetadata_Deserialize = ConnectionMetadataWire_Deserialize

export type ConnectionMetadata_Serialize = {
  /**  See [`Connection::extra`]. */
  _extra: { [key in string]: JsonValue | null }
} & ConnectionMetadataFields_Serialize

export type ConnectionNetwork = 'tcp' | 'udp' | 'all' | 'invalid'

export type ConnectionType =
  | 'HTTP'
  | 'HTTPS'
  | 'Socks4'
  | 'Socks5'
  | 'ShadowSocks'
  | 'Snell'
  | 'Vmess'
  | 'Vless'
  | 'Redir'
  | 'TProxy'
  | 'Trojan'
  | 'Tunnel'
  | 'Tun'
  | 'Tuic'
  | 'Hysteria2'
  | 'AnyTLS'
  | 'Mieru'
  | 'Sudoku'
  | 'TrustTunnel'
  | 'ShadowQuic'
  | 'Inner'
  | 'Unknown'

/**
 *  Deserialize-only mirror of [`Connection`], with unknown fields flattened
 *  the way Mihomo sends them. [`Connection`]'s `Deserialize` impl delegates
 *  here via `#[serde(from = "ConnectionWire")]` so serialization can use a
 *  different, named shape for `extra` (see [`Connection::extra`]).
 */
export type ConnectionWire =
  ConnectionWire_Serialize | ConnectionWire_Deserialize

/**
 *  Deserialize-only mirror of [`Connection`], with unknown fields flattened
 *  the way Mihomo sends them. [`Connection`]'s `Deserialize` impl delegates
 *  here via `#[serde(from = "ConnectionWire")]` so serialization can use a
 *  different, named shape for `extra` (see [`Connection::extra`]).
 */
export type ConnectionWire_Deserialize = {
  id: string
  metadata: ConnectionMetadata_Deserialize | null
  upload: number
  download: number
  start: string
  chains: string[]
  providerChains?: string[] | null
  rule: string
  rulePayload: string
} & { [key in string]: JsonValue | null }

/**
 *  Deserialize-only mirror of [`Connection`], with unknown fields flattened
 *  the way Mihomo sends them. [`Connection`]'s `Deserialize` impl delegates
 *  here via `#[serde(from = "ConnectionWire")]` so serialization can use a
 *  different, named shape for `extra` (see [`Connection::extra`]).
 */
export type ConnectionWire_Serialize = {
  id: string
  metadata: ConnectionMetadata_Serialize | null
  upload: number
  download: number
  start: string
  chains: string[]
  providerChains: string[] | null
  rule: string
  rulePayload: string
} & { [key in string]: JsonValue | null }

export type Connection_Deserialize = ConnectionWire_Deserialize

export type Connection_Serialize = {
  id: string
  metadata: ConnectionMetadata_Serialize | null
  upload: number
  download: number
  start: string
  chains: string[]
  providerChains?: string[] | null
  rule: string
  rulePayload: string
  /**
   *  Fields Mihomo returns that this type does not yet model. Deserializing
   *  (from Mihomo) collects unknown keys here regardless of direction;
   *  serializing (for our own IPC) emits them under this named key instead
   *  of flattening them, so a future Mihomo field literally named `extra`
   *  cannot collide with it.
   */
  _extra: { [key in string]: JsonValue | null }
}

export type ConvergenceHealth =
  | 'healthy'
  | 'pending'
  | 'retry_scheduled'
  | 'waiting_dependency'
  | 'blocked'
  | 'recovery_required'

/**
 *  The core's control endpoint, as the manager resolved it.
 *
 *  A deliberately separate type from `clash_api::Host`: clash-api is an
 *  internal dependency of the core manager and must not leak into the wire
 *  dependency tree. The controller secret is never carried here. Clients read
 *  applied credentials through the private `/v2/core/api-connection` endpoint;
 *  the IPC transport's authorization gate is the socket ACL.
 */
export type CoreControllerInfo =
  | ({ NamedPipe: string } & { Http?: never; UnixSocket?: never })
  | ({ UnixSocket: string } & { Http?: never; NamedPipe?: never })
  /**  Normalized base URL with any credentials removed. */
  | ({ Http: string } & { NamedPipe?: never; UnixSocket?: never })

export type CoreErrorKind =
  | 'native_store_unavailable'
  /**  The operation needs a running core and there is none. */
  | 'not_started'
  /**  The operation needs a stopped core and one is running. */
  | 'already_running'
  /**
   *  `expected_revision` did not match the running revision. Nothing was
   *  applied; re-read `/status` for the current one and retry.
   */
  | 'revision_conflict'
  /**
   *  An epoch whose death could not be confirmed has latched the manager.
   *  Every lifecycle operation is refused until a `Recover` submission clears it.
   */
  | 'quarantined'
  /**  The core itself rejected the config in a dry run. */
  | 'config_check_failed'
  | 'config_not_found'
  | 'binary_not_found'
  /**  The config could not be parsed or canonicalized. */
  | 'invalid_config'
  /**
   *  The config declares no external controller, so the core cannot be
   *  health-probed.
   */
  | 'controller_missing'
  /**  The apply failed and the previous revision was restored. */
  | 'apply_failed'
  /**  The apply failed and so did the rollback: no epoch is running. */
  | 'apply_rollback_failed'
  /**  A core process could not be proven dead; the manager is now quarantined. */
  | 'stop_unconfirmed'
  /**  The control plane is shutting down and admits no new operations. */
  | 'shutting_down'
  /**  The bounded operation queue is full; retry after in-flight work drains. */
  | 'queue_full'
  /**
   *  The `OperationId` was already used with a different payload, or the
   *  operation cannot run concurrently with one that owns the endpoint
   *  (for example a host handoff in progress).
   */
  | 'operation_conflict'
  /**
   *  The control endpoint cannot be reached: transport failure, daemon not
   *  running, or the endpoint is reconnecting. Retryable by definition.
   */
  | 'backend_unavailable'
  /**
   *  The control plane itself failed — an executor died or a reply channel
   *  broke. Not retryable; the host must treat this as fatal.
   */
  | 'internal'

/**
 *  The wire mirror of a [`CoreError`], which is a foreign type without serde.
 *  It is the only place a `CoreError` is unpacked for the frontend.
 */
export type CoreFailure = {
  /**  `None` when the core manager did not classify the failure. */
  kind: CoreErrorKind | null
  message: string
  retryable: boolean
  operation_id: string | null
}

/**
 *  The manager's health observation for the active core. Absent while the
 *  core is stopping or stopped.
 */
export type CoreHealthInfo = {
  state: CoreHealthState
  /**  Unix milliseconds of the last health-state transition. */
  changed_at: number
  consecutive_failures: number
  /**  Last probe failure detail, capped by the manager at 512 bytes. */
  last_error: string | null
  /**  Unix milliseconds of the last successful probe. */
  last_success_at: number | null
}

/**  Health observation state for the active core. */
export type CoreHealthState = 'Starting' | 'Healthy' | 'Unhealthy'

export type CoreInfos = CoreInfos_Serialize | CoreInfos_Deserialize

export type CoreInfos_Deserialize = {
  instance_id?: string | null
  type: CoreType | null
  state: CoreState
  state_changed_at: number
  config_path: string | null
  /**
   *  Omitted rather than null when absent, so a payload carrying none of
   *  the fields below is byte-identical to the pre-S7 wire format.
   */
  controller?: CoreControllerInfo | null
  health?: CoreHealthInfo | null
  revision?: ConfigRevisionInfo | null
  detail?: CoreStateDetail | null
}

export type CoreInfos_Serialize = {
  instance_id?: string | null
  type: CoreType | null
  state: CoreState
  state_changed_at: number
  config_path: string | null
  /**
   *  Omitted rather than null when absent, so a payload carrying none of
   *  the fields below is byte-identical to the pre-S7 wire format.
   */
  controller?: CoreControllerInfo | null
  health?: CoreHealthInfo | null
  revision?: ConfigRevisionInfo | null
  detail?: CoreStateDetail | null
}

/**  A failure of locating the binary a core is started from. */
export type CoreSpecError =
  | { kind: 'find_core_binary'; core: string }
  | { kind: 'core_binary_path_not_utf8'; core: string; path: string }

export type CoreState = 'Running' | { Stopped: string | null }

/**
 *  The core's full lifecycle state.
 *
 *  [`CoreState`] is a two-valued projection kept for wire compatibility: it
 *  reports `Starting` and `Restarting` as `Stopped(None)`, so a crash loop is
 *  indistinguishable from a real stop. This is the faithful view; prefer it
 *  when present.
 */
export type CoreStateDetail =
  | ({
      Stopped: {
        reason: string | null
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Starting: {
        epoch: number
      }
    } & {
      Restarting?: never
      Running?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Running: {
        epoch: number
        pid: number
      }
    } & {
      Restarting?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Restarting: {
        epoch: number
        attempt: number
      }
    } & {
      Running?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
      Switching?: never
    })
  | ({
      Switching: {
        from: number | null
        to: number
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopped?: never
      Stopping?: never
    })
  | ({
      Stopping: {
        epoch: number
      }
    } & {
      Restarting?: never
      Running?: never
      Starting?: never
      Stopped?: never
      Switching?: never
    })

export type CoreStatusChangedEvent = CoreStatusInfo

export type CoreStatusInfo = {
  controller: CoreControllerInfo | null
  host: ExecutionHost
  connectivity: EndpointConnectivity
  generation: number
  state: CoreStateDetail | null
  state_changed_at: number
  revision: RevisionIdInfo | null
  healthy: boolean | null
}

export type CoreType = { clash: ClashCoreType } | 'singbox'

/**  A failure of asking a core binary for its version. */
export type CoreVersionError =
  | { kind: 'run_core_version'; core: string }
  | { kind: 'core_version_exit'; core: string }
  | { kind: 'core_version_not_reported'; core: string }

export type DnsMode = 'normal' | 'fake-ip' | 'redir-host' | 'hosts' | 'Unknown'

export type EffectConvergence = {
  kind: EffectKind
  health: ConvergenceHealth
  desired_revision: number
  applied_revision: number
  attempts: number
  automatic_remaining: number
  /**  What kind of failure the effect is in, for the UI to localize. */
  code: EffectFailureCode | null
  /**  The failure's diagnostic text, as the owner reported it. */
  message: string | null
}

/**
 *  Why an effect is not in its desired state, in the terms the UI localizes.
 *
 *  One value per kind of failure, named after the effect that failed. The
 *  owner that classifies a failure is the one that picks the code; the
 *  message beside it is only the diagnostic text.
 */
export type EffectFailureCode =
  | 'hotkey_invalid_bindings'
  | 'hotkey_partial_registration'
  | 'hotkey_shut_down'
  | 'hotkey_stopped'
  | 'logger_refresh_failed'
  | 'widget_unavailable'
  | 'widget_apply_failed'
  | 'tray_refresh_failed'
  | 'effect_owner_silent'
  | 'proxy_guard_waiting_dependency'
  | 'auto_launch_failed'
  | 'pac_disable_failed'
  | 'pac_apply_failed'
  | 'pac_unsupported'
  | 'system_proxy_apply_failed'
  | 'system_proxy_port_unresolved'
  | 'system_proxy_restore_failed'
  | 'system_proxy_shut_down'
  | 'system_proxy_stopped'

/**
 *  Execution order of a plan. The ordering is load-bearing: the tray menu is
 *  rendered with the process-wide locale, and the proxy guard re-applies the
 *  system proxy value that the `SystemProxy` effect just installed.
 */
export type EffectKind =
  | 'locale'
  | 'logger'
  | 'auto_launch'
  | 'system_proxy'
  | 'proxy_guard'
  | 'hotkeys'
  | 'widget'
  | 'tray'

export type EffectsError =
  /**  The owner's mailbox is closed: the app is exiting, or the owner died. */
  { kind: 'effects_stopped' }

export type EndpointConnectivity =
  | { kind: 'connected' }
  | { kind: 'shut_down' }
  | { kind: 'handing_off'; from: ExecutionHost; to: ExecutionHost }
  /**
   *  The endpoint is unreachable. `desired` names the committed host; the
   *  router never falls back on its own.
   */
  | { kind: 'degraded'; desired: ExecutionHost; reason: string }

/**
 *  A filesystem path as it appears in an error. The lossy conversion keeps it
 *  serializable when the path is not valid UTF-8.
 */
export type ErrorPath = string

/**
 *  Evidence a mutation needed and did not have, before anything was tried.
 *
 *  Not a Try outcome. Nothing was submitted, so there is no result to classify
 *  and this attempt made nothing less certain than it already was — which is
 *  why it is a plain refusal the caller may retry (v2 §2.4, first row) and
 *  never the isolated state §11.4 reserves for "结果可能已经执行".
 */
export type EvidenceGap =
  /**
   *  The core is mid-transition — starting, restarting, switching or
   *  stopping. That is an answer, but not one that says what a candidate
   *  would be applied on top of.
   */
  | 'core_transitioning'
  /**
   *  The host published no runtime state, or the read failed, and no stop
   *  this workflow recorded settles the question either.
   */
  | 'baseline_unconfirmed'
  /**
   *  A core is running that this session never applied to, so no receipt
   *  describes what it is running. The Try could be submitted, but its Cancel
   *  would have nothing to put back — and a mutation that cannot be undone
   *  must not be attempted (R10). The gap is known before anything is
   *  submitted, which is what keeps it a refusal rather than the isolated
   *  state a post-submission unknown earns.
   */
  | 'no_restorable_baseline'

/**
 *  Which controller owns the runtime. The app perceives the difference in
 *  exactly two places: this tag on the endpoint slot, and the handoff
 *  protocol.
 */
export type ExecutionHost = 'local' | 'service'

/**  What a path was required to be when it was not. */
export type ExpectedNode =
  | 'real_directory'
  | 'regular_file'
  /**  A regular file, or a symlink whose target is read as text. */
  | 'hashable_target'
  /**  Absent, a regular file, or a symlink. */
  | 'replaceable_target'
  /**  Anything but a directory. */
  | 'removable_resource'
  /**  Absent, or a symlink to the staged target. */
  | 'ready_symlink'

/**  An absolute path outside the managed profile directory. */
export type ExternalProfilePath = string

/**
 *  What a hotkey does. The strings are the on-disk and on-wire identifiers, so
 *  they are fixed by the configurations users already have.
 */
export type HotkeyAction =
  | 'open_or_close_dashboard'
  | 'clash_mode_rule'
  | 'clash_mode_global'
  | 'clash_mode_direct'
  | 'clash_mode_script'
  | 'toggle_system_proxy'
  | 'enable_system_proxy'
  | 'disable_system_proxy'
  | 'toggle_tun_mode'
  | 'enable_tun_mode'
  | 'disable_tun_mode'

/**
 *  Why a hotkey list could not be accepted. Rejected before anything is
 *  committed, so every variant names the entry the user has to fix.
 */
export type HotkeyParseError =
  /**  Not the `"<function>,<accelerator>"` shape. */
  | { kind: 'malformed_entry'; entry: string }
  | { kind: 'unknown_function'; function: string }
  /**  A `+` separated accelerator with an empty segment. */
  | { kind: 'empty_key_segment'; accelerator: string }
  /**
   *  The platform's parser refused it; its text, which names the offending
   *  key, reaches the user only through the copied detail. Boxed because
   *  this module does not name the plugin.
   */
  | { kind: 'unsupported_accelerator'; accelerator: string }
  | { kind: 'missing_super_key'; accelerator: string }
  /**  The same accelerator was bound to two functions. */
  | {
      kind: 'duplicate_accelerator'
      accelerator: string
      first: HotkeyAction
      second: HotkeyAction
    }

/**  A failure of installing a downloaded core binary over the installed one. */
export type InstallCoreBinaryError =
  | { kind: 'start_elevated_copy'; core: string; destination: ErrorPath }
  | {
      kind: 'elevated_copy_failed'
      core: string
      destination: ErrorPath
      exit_code: number | null
    }
  | { kind: 'path_not_utf8'; path: ErrorPath }

/**  A failed command as the frontend receives it. */
export type IpcError = {
  /**  The domain failure; the frontend localizes it. */
  kind: IpcErrorKind
  /**  The error's own message, shown when `kind` cannot be localized. */
  message: string
  /**  The original error, copied by the user for diagnosis. */
  detail: string
}

/**  The domain a command failed in. A domain joins once its errors are typed. */
export type IpcErrorKind =
  /**  Not classified into a domain; only `message` describes it. */
  | { domain: 'unknown' }
  | { domain: 'profiles'; error: ProfilesError }
  | { domain: 'runtime'; error: RuntimeError }
  | { domain: 'config'; error: ConfigError }
  | { domain: 'storage'; error: StorageOperationError }
  | { domain: 'system_dns'; error: SystemDnsError }
  | { domain: 'system_proxy'; error: OsProxyError }
  | { domain: 'effects'; error: EffectsError }

/**
 *  Type-only description of an arbitrary JSON value, used to give the `extra`
 *  maps below (see [`Connection::extra`], [`ConnectionMetadata::extra`]) a
 *  named, exportable specta shape. Never constructed or serialized itself;
 *  the actual runtime data stays `serde_json::Value`.
 */
export type JsonValue =
  | boolean
  | number
  | null
  | string
  | (JsonValue | null)[]
  | { [key in string]: JsonValue | null }

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream. The service's own files are queried through the bounded
 *  `/v1/logs/*` session RPCs when `log_query_version` is present; directory
 *  permissions remain unchanged and these logs never enter the event stream.
 */
export type LogPathsInfo = LogPathsInfo_Serialize | LogPathsInfo_Deserialize

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream. The service's own files are queried through the bounded
 *  `/v1/logs/*` session RPCs when `log_query_version` is present; directory
 *  permissions remain unchanged and these logs never enter the event stream.
 */
export type LogPathsInfo_Deserialize = {
  /**
   *  The service's own logs: JSON lines from `tracing-appender`, rotated
   *  daily, seven files kept.
   */
  service_dir: string
  /**
   *  The core log archive: one rolling JSONL stream, rotated by size and
   *  retained by count. Absent when the manager's sink is switched off, in
   *  which case no such directory exists at all.
   */
  core_dir?: string | null
}

/**
 *  Where this service writes logs.
 *
 *  These are the service's own facts, not an echo of what the caller passed at
 *  start-up, which is why they are here and not in [`RuntimeInfos`].
 *
 *  **These are locations, not a grant.** Both directories are restricted to the
 *  account the service runs under plus local administrators, so a caller
 *  running as an ordinary user generally cannot read them — surface the path
 *  for a support request rather than building a tail on it. Live core output is
 *  on the event stream. The service's own files are queried through the bounded
 *  `/v1/logs/*` session RPCs when `log_query_version` is present; directory
 *  permissions remain unchanged and these logs never enter the event stream.
 */
export type LogPathsInfo_Serialize = {
  /**
   *  The service's own logs: JSON lines from `tracing-appender`, rotated
   *  daily, seven files kept.
   */
  service_dir: string
  /**
   *  The core log archive: one rolling JSONL stream, rotated by size and
   *  retained by count. Absent when the manager's sink is switched off, in
   *  which case no such directory exists at all.
   */
  core_dir?: string | null
}

/**  A path relative to the application-managed profile directory. */
export type ManagedProfilePath = string

/**  What the materialization port was doing when it failed. */
export type MaterializationOperation =
  | 'prepare_file_first'
  | 'compensate'
  | 'complete'
  | 'prepare_cleanup'
  | 'activate_cleanup'
  | 'cancel_cleanup'
  | 'retry_cleanup'
  | 'reconcile'

export type OperationStatus = {
  operation_id: string
  domain: string
  outcome: string
  conclusion: string
  message: string | null
}

/**  The pipeline operator that produced a snapshot node. */
export type OperatorTag =
  | {
      kind: 'file_config_root'
      data: {
        profile_id: ProfileId
        role: ConfigExecutionRole
      }
    }
  /**  `base: None` is the clean seed (`proxies: []`). */
  | {
      kind: 'composition_root'
      data: {
        profile_id: ProfileId
        base: ProfileId | null
      }
    }
  | {
      kind: 'extend_proxies_step'
      data: {
        composition_id: ProfileId
        contributor_profile_id: ProfileId
        contributor_index: number
      }
    }
  | {
      kind: 'scoped_transform'
      data: {
        host_profile_id: ProfileId
        role: ConfigExecutionRole
        transform_profile_id: ProfileId
        transform_kind: TransformKind
        step_index: number
      }
    }
  /**  `selected_profile_id: None` = bare 模式（current 为空，spec §2 目标 6）。 */
  | {
      kind: 'global_transform'
      data: {
        selected_profile_id: ProfileId | null
        transform_profile_id: ProfileId
        transform_kind: TransformKind
        step_index: number
      }
    }
  | {
      kind: 'builtin_step'
      data: {
        selected_profile_id: ProfileId | null
        step: BuiltinStepKind
      }
    }
  /**  current = None 的裸配置管线根（spec §8.2）。 */
  | { kind: 'bare_root' }
  /**  内建增强脚本步骤；`name` 为展示性字段，`node_key()` 丢弃。 */
  | {
      kind: 'builtin_transform'
      data: {
        selected_profile_id: ProfileId | null
        name: string
        step_index: number
      }
    }

/**
 *  Why the platform proxy settings could not be read or written. The platform's
 *  own error stays in `source`, boxed because this module does not name the
 *  crate that produced it; it reaches the user through the copied detail.
 */
export type OsProxyError =
  | { kind: 'read_os_proxy' }
  | { kind: 'write_os_proxy'; enable: boolean; host: string; port: number }

export type PickPortError =
  { kind: 'port_not_available'; port: number } | { kind: 'no_open_port' }

/**  The port a resolution was picking for. */
export type PortField = 'mixed' | 'http' | 'socks' | 'external_controller'

/**  A failure of resolving the ports a candidate runtime would bind. */
export type PortResolveError = {
  kind: 'resolve_port'
  field: PortField
  source: PickPortError
}

/**  Downloaded or read content that is not a valid profile document. */
export type ProfileContentError =
  | { kind: 'not_yaml_mapping' }
  | { kind: 'reserialize_yaml' }
  | { kind: 'missing_proxies' }
  | { kind: 'empty_script' }

/**
 *  A failure of the profile filesystem, its materialization journals or its
 *  private storage. One type for both the profile filesystem port and the
 *  materialization port, whose implementations share their helpers.
 */
export type ProfileFileError =
  | { kind: 'inspect_path'; path: ErrorPath }
  | { kind: 'read_file'; path: ErrorPath }
  | { kind: 'read_link'; path: ErrorPath }
  | { kind: 'write_file'; path: ErrorPath }
  | { kind: 'atomic_write'; path: ErrorPath }
  | { kind: 'create_directory'; path: ErrorPath }
  | { kind: 'remove_file'; path: ErrorPath }
  | { kind: 'replace_file'; from: ErrorPath; to: ErrorPath }
  | { kind: 'create_symlink'; link: ErrorPath; target: ErrorPath }
  | { kind: 'list_directory'; path: ErrorPath }
  | { kind: 'sync_directory'; path: ErrorPath }
  | { kind: 'set_permissions'; path: ErrorPath }
  | { kind: 'canonicalize_path'; path: ErrorPath }
  | { kind: 'read_external_target'; target: ExternalProfilePath }
  | { kind: 'parse_journal'; path: ErrorPath }
  | { kind: 'serialize_journal' }
  | { kind: 'reserved_path'; path: ErrorPath }
  | { kind: 'path_escapes_profiles_dir'; path: ErrorPath; root: ErrorPath }
  | { kind: 'no_parent_directory'; path: ErrorPath }
  | { kind: 'unexpected_node'; path: ErrorPath; expected: ExpectedNode }
  | { kind: 'unexpected_symlink'; path: ErrorPath }
  | { kind: 'existing_file_blocks_symlink'; path: ErrorPath }
  | { kind: 'symlink_target_not_utf8'; path: ErrorPath }
  | { kind: 'invalid_external_path' }
  | { kind: 'cleanup_tombstone_exists'; path: ErrorPath }
  | { kind: 'journal_not_found'; operation_id: string }
  | { kind: 'compensation_fenced'; path: ErrorPath }
  | { kind: 'operation_id_invalid' }
  | { kind: 'operation_id_exhausted' }
  | { kind: 'journal_operation_id_mismatch' }
  | { kind: 'journal_hash_invalid' }
  | { kind: 'mixed_transaction_families' }
  | { kind: 'conflicting_journal_payloads' }
  | { kind: 'journal_destination_differs' }
  | { kind: 'conflicting_cleanup_payloads' }
  | { kind: 'multiple_staged_resources' }
  | { kind: 'multiple_backups' }
  | { kind: 'staged_hash_mismatch' }
  | { kind: 'ready_symlink_mismatch' }
  | { kind: 'staged_resource_missing' }
  | { kind: 'promoted_hash_mismatch' }
  | { kind: 'compensating_cannot_promote' }
  | { kind: 'target_hash_mismatch' }
  | { kind: 'not_completable' }
  | { kind: 'cleanup_already_activated' }
  | { kind: 'diverged_before_recovery' }

/**  Stable profile identifier. It is also the key used by [`Profiles::items`]. */
export type ProfileId = string

export type ProfileValidationError =
  | ({
      ItemKeyMismatch: {
        key: ProfileId
        item_uid: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({ CurrentNotFound: ProfileId } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({ CurrentNotConfig: ProfileId } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      TransformTargetNotFound: {
        owner: TransformOwner
        target: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      TransformTargetNotTransform: {
        owner: TransformOwner
        target: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      EmptyCompositionConfig: {
        composition: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionSelfReference: {
        composition: ProfileId
        role: CompositionMemberRole
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionMemberNotFound: {
        composition: ProfileId
        role: CompositionMemberRole
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionMemberNotDirectFileConfig: {
        composition: ProfileId
        role: CompositionMemberRole
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionBaseAlsoContributor: {
        composition: ProfileId
        profile: ProfileId
      }
    } & {
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      CompositionDuplicateContributor: {
        composition: ProfileId
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      DuplicateMaterializedFile: {
        file: ManagedProfilePath
        first: ProfileId
        second: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })
  | ({
      UnsupportedRemoteUrlScheme: {
        profile: ProfileId
        scheme: string
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      RemoteUpdateIntervalIsZero?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
    })
  | ({
      RemoteUpdateIntervalIsZero: {
        profile: ProfileId
      }
    } & {
      CompositionBaseAlsoContributor?: never
      CompositionDuplicateContributor?: never
      CompositionMemberNotDirectFileConfig?: never
      CompositionMemberNotFound?: never
      CompositionSelfReference?: never
      CurrentNotConfig?: never
      CurrentNotFound?: never
      DuplicateMaterializedFile?: never
      EmptyCompositionConfig?: never
      ItemKeyMismatch?: never
      TransformTargetNotFound?: never
      TransformTargetNotTransform?: never
      UnsupportedRemoteUrlScheme?: never
    })

/**  What a profile command failed with. */
export type ProfilesError =
  | { kind: 'profile_not_found'; uid: ProfileId }
  | { kind: 'profile_has_no_file'; uid: ProfileId }
  | { kind: 'not_a_remote_profile'; uid: ProfileId }
  | { kind: 'profile_file_not_writable'; uid: ProfileId }
  | {
      kind: 'profile_in_use'
      uid: ProfileId
      referrers: ProfileId[]
      /**  Referenced by the document-level `current` selection. */
      current: boolean
      /**  Referenced by the document-level `global_transforms` list. */
      global_transforms: boolean
    }
  | { kind: 'profile_id_collision'; uid: ProfileId }
  | { kind: 'validation_failed'; errors: ProfileValidationError[] }
  | { kind: 'reorder_list_size_mismatch'; expected: number; got: number }
  | { kind: 'reorder_list_duplicate'; uid: ProfileId }
  | { kind: 'revision_overflow' }
  | { kind: 'invalid_subscription_url'; url: string }
  | { kind: 'remote_profile_needs_import' }
  | { kind: 'refresh_in_progress'; uid: ProfileId }
  | { kind: 'fetch_subscription'; url: string; source: SubscriptionFetchError }
  | { kind: 'profile_content_rejected'; source: ProfileContentError }
  | { kind: 'profile_deleted_during_refresh'; uid: ProfileId }
  | { kind: 'profile_changed_during_refresh'; uid: ProfileId }
  | { kind: 'fingerprint_definition'; uid: ProfileId }
  | { kind: 'read_profile_file'; uid: ProfileId; source: ProfileFileError }
  | {
      kind: 'profile_file_not_yaml'
      uid: ProfileId
      source: ProfileContentError
    }
  | { kind: 'profile_file_missing'; uid: ProfileId; path: ErrorPath }
  | {
      kind: 'read_external_profile'
      target: ExternalProfilePath
      source: ProfileFileError
    }
  | {
      kind: 'materialization'
      operation: MaterializationOperation
      source: ProfileFileError
    }
  | { kind: 'version_conflict'; expected: number; actual: number }
  | { kind: 'commit'; source: CommitAborted }
  | { kind: 'workflow_not_ready' }
  | { kind: 'profiles_actor_stopped' }
  | { kind: 'profiles_reply_dropped' }
  | { kind: 'blocking_task_cancelled' }
  | { kind: 'shutting_down' }

/**  A failure of publishing the derived runtime config file. */
export type PublishRuntimeError =
  | { kind: 'create_runtime_directory'; path: ErrorPath }
  | { kind: 'write_runtime_config'; path: ErrorPath }

export type ReleaseChannel = 'stable' | 'beta' | 'nightly'

/**  Why the runtime baseline could not be put back. */
export type RestoreFailure =
  | { kind: 'move_host_back'; host: ExecutionHost; failure: CoreFailure }
  | { kind: 'read_status'; failure: CoreFailure }
  /**
   *  The runtime could not be read once the restore request had answered;
   *  `failure` is that request's own failure, if it had one.
   */
  | { kind: 'unobserved'; failure: CoreFailure | null }
  | { kind: 'unverified'; failure: CoreFailure | null }
  /**  The configuration the core ran before was never recorded. */
  | { kind: 'not_recorded' }

/**
 *  The compare-and-swap identity of a config revision.
 *
 *  Deliberately a subset of [`ConfigRevisionInfo`]: the manager's CAS compares
 *  epoch, generation and `effective_hash` only, so carrying `source_hash` here
 *  would imply it takes part.
 */
export type RevisionIdInfo = {
  epoch: number
  generation: number
  effective_hash: string
}

export type RpcError = {
  kind: string
  message: string
  code: string | null
  retryable: boolean | null
  operation_id: string | null
  domain_error: RpcValue | null
}

/**
 *  Specta 0.0.12 cannot recursively export `serde_json::Value` directly.
 *  Keep the JSON wire transparent while exporting it as TypeScript `any`.
 */
export type RpcValue = any

/**
 *  What became of the runtime after an aborted commit, from the receipt's
 *  structured fields. `detail` is the receipt's operator diagnostics, never an
 *  input to a decision.
 */
export type RuntimeAftermath =
  /**  The runtime took no part, or the transaction withdrew before it did. */
  | { kind: 'untouched' }
  /**  The runtime went back to the previous configuration. */
  | { kind: 'rolled_back' }
  /**  Rolling the runtime back failed; recovery is required. */
  | { kind: 'rollback_failed'; detail: RuntimeError }
  /**  What the runtime is running is unknown and needs recovery. */
  | { kind: 'unknown'; detail: RuntimeError }

/**  A failure of building a runtime candidate from source config. */
export type RuntimeBuildError =
  | { kind: 'start_script_runner' }
  | { kind: 'validate_profiles'; errors: ProfileValidationError[] }
  | { kind: 'run_pipeline'; source: RuntimePipelineError }
  | {
      kind: 'transforms_failed'
      failures: TransformFailure[]
      logs: RuntimeBuildLog[]
    }
  | { kind: 'serialize_final_config' }
  | { kind: 'config_not_mapping' }
  | { kind: 'serialize_runtime_config' }

export type RuntimeBuildLog = {
  tag: OperatorTag
  entries: StepLogEntry[]
}

/**
 *  Why no check ran. Every variant is a reason, never a verdict: an absent
 *  check must not be reported as a passing one (v2 §2.4).
 */
export type RuntimeCheckUnavailable =
  /**  No host owns the runtime, so there is nothing to check against. */
  | { cause: 'no_endpoint'; reason: string }
  /**  The host owning the runtime exposes no check for this request. */
  | { cause: 'host_unsupported'; host: ExecutionHost; reason: string }
  /**  The host reads the candidate from disk and it could not be staged. */
  | { cause: 'candidate_unavailable'; reason: string }
  /**  The host has the capability but could not serve it. */
  | {
      cause: 'backend'
      kind: CoreErrorKind | null
      message: string
      retryable: boolean
    }

export type RuntimeConvergence = {
  health: ConvergenceHealth
  operation_id: string | null
  attempts: number
  automatic_remaining: number
  message: string | null
}

/**  A failure of an operation on the running core or the runtime workflow. */
export type RuntimeError =
  /**  Refused at admission: nothing ran. */
  | { kind: 'shutting_down' }
  /**  Refused at admission: nothing ran. */
  | { kind: 'isolated' }
  /**  The workflow took the command and never answered, so it may have run. */
  | { kind: 'owner_unresponsive'; operation_id: string }
  /**  Refused at admission: the runtime owner is gone, so nothing ran. */
  | { kind: 'owner_unavailable' }
  /**  Refused at admission: the source transaction had already been decided. */
  | { kind: 'source_settled' }
  | { kind: 'apply_runtime'; failure: CoreFailure }
  | { kind: 'stop_core'; failure: CoreFailure }
  | { kind: 'recover_runtime'; failure: CoreFailure }
  | { kind: 'recover_service_endpoint'; failure: CoreFailure }
  | { kind: 'refresh_status'; failure: CoreFailure }
  | { kind: 'install_service'; failure: CoreFailure }
  | { kind: 'start_service'; failure: CoreFailure }
  | { kind: 'stop_service'; failure: CoreFailure }
  | { kind: 'restart_service'; failure: CoreFailure }
  | { kind: 'uninstall_service'; failure: CoreFailure }
  | { kind: 'move_host'; host: ExecutionHost; failure: CoreFailure }
  /**  The service hosts the runtime; the local host must take it over first. */
  | { kind: 'service_hosts_core' }
  /**
   *  An explicit start that could not put the core on its host; `reason` is
   *  the diagnostic text of the convergence that gave up.
   */
  | { kind: 'core_not_started'; reason: string; retryable: boolean }
  /**  An explicit recovery that could not settle the runtime. */
  | { kind: 'recovery_unresolved'; reason: string }
  | { kind: 'build_runtime'; source: RuntimeBuildError }
  | { kind: 'publish_runtime'; source: PublishRuntimeError }
  | { kind: 'resolve_port'; source: PortResolveError }
  | { kind: 'resolve_core_binary'; source: CoreSpecError }
  | { kind: 'install_core_binary'; source: InstallCoreBinaryError }
  | { kind: 'prepare_service_install_prompt'; source: ServiceCommandError }
  | { kind: 'read_core_version'; source: CoreVersionError }
  /**
   *  A candidate was refused before anything was submitted, for want of a
   *  baseline to apply against.
   */
  | { kind: 'unsettled_baseline'; gap: EvidenceGap }
  | {
      kind: 'core_rejected_config'
      core_kind: CoreErrorKind | null
      message: string
    }
  | { kind: 'check_unavailable'; reason: RuntimeCheckUnavailable }
  /**  The core restored its own previous configuration. */
  | { kind: 'core_rolled_back'; reason: string | null }
  /**  The submission ended unobserved, so it may have taken effect. */
  | { kind: 'submission_unobserved'; failure: CoreFailure }
  | { kind: 'handoff_owner_mismatch'; expected: ExecutionHost }
  /**
   *  A mutation that moved the runtime to the other host and failed there
   *  could not put it back.
   */
  | { kind: 'handoff_not_restored'; failure: RestoreFailure }
  /**  A cancelled mutation could not put the runtime back. */
  | { kind: 'restore_failed'; failure: RestoreFailure }
  /**
   *  The store committed a mutation whose runtime target the workflow had
   *  refused.
   */
  | { kind: 'committed_after_refusal'; operation_id: string }
  /**  No runtime configuration has been built yet. */
  | { kind: 'no_runtime_config' }
  | { kind: 'serialize_runtime_config' }
  | { kind: 'convert_runtime_config' }
  /**  A newer build replaced the snapshot the inspection was opened on. */
  | { kind: 'runtime_snapshot_changed' }
  | { kind: 'runtime_node_not_found'; node_id: number }

export type RuntimeInfos = {
  service_data_dir: string
  service_config_dir: string
  nyanpasu_config_dir: string
  nyanpasu_data_dir: string
}

/**
 *  Wire shape for the app's error channel: library sources are skipped and
 *  reach the user only through the error's `Debug` detail.
 */
export type RuntimePipelineError =
  | { kind: 'selected_profile_not_found'; profile: ProfileId }
  | { kind: 'selected_profile_not_config'; profile: ProfileId }
  | {
      kind: 'composition_member_invalid'
      composition: ProfileId
      member: ProfileId
      reason: string
    }
  | { kind: 'content_source'; profile: ProfileId; path: ManagedProfilePath }
  | { kind: 'parse_profile'; profile: ProfileId; message: string }
  | { kind: 'snapshot' }
  /**  Theoretically unreachable invariant breaks (e.g. guard serialization). */
  | { kind: 'internal'; message: string }

/**
 *  Emitted to the frontend after a `clash-nyanpasu`/`clash` custom-scheme deep
 *  link joins [`PendingDeepLinks`]. It carries no URL: it only asks a listening
 *  frontend to take the queue through [`take_pending_deep_links`].
 *
 *  Event name: `scheme-request-received-event` (derived by `tauri_specta`).
 */
export type SchemeRequestReceivedEvent = null

export type ScriptRuntime = 'javascript' | 'lua'

/**  The elevated operations `nyanpasu-service` is asked to perform. */
export type ServiceCommand =
  'install' | 'update' | 'uninstall' | 'start' | 'stop' | 'restart'

/**
 *  A failure of running or querying the system service, including the bounds
 *  the service actor puts on every call.
 */
export type ServiceCommandError =
  | { kind: 'resolve_service_user' }
  | { kind: 'resolve_service_dirs' }
  | { kind: 'run_elevated'; command: ServiceCommand }
  | {
      kind: 'service_command_exit'
      command: ServiceCommand
      exit_code: number | null
      signal: number | null
    }
  | { kind: 'run_service_status' }
  | {
      kind: 'service_status_exit'
      exit_code: number | null
      signal: number | null
    }
  | { kind: 'service_status_not_utf8' }
  | { kind: 'parse_service_status' }
  | { kind: 'timed_out'; limit_ms: number }
  | { kind: 'still_running'; limit_ms: number }
  | { kind: 'task_cancelled' }

export type ServiceCompat =
  /**  daemon 未安装 / 未运行 / 未上报 server 信息，没有可判定的版本。 */
  | { kind: 'unknown' }
  /**  主版本匹配，允许进入 Service backend。 */
  | { kind: 'compatible'; server_version: string }
  /**
   *  主版本不匹配（典型：v1.4.5），或主版本对但低于最低版本（典型：
   *  v2.0.0-rc.1）。fail-closed。
   */
  | {
      kind: 'incompatible'
      server_version: string
      required_major: number
      /**
       *  供 UI 展示：只说"需要 v2.x"无法解释一台 major 正确却被拒的
       *  daemon，它装的**就是** v2.x。
       */
      required_min: string
    }
  /**  server 上报的版本不是合法 semver。fail-closed。 */
  | { kind: 'unparsable'; server_version: string }

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus =
  ServiceHostStatus_Serialize | ServiceHostStatus_Deserialize

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus_Deserialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Deserialize | null
  phase: ServicePhase
  compat: ServiceCompat
  restart_attempts: number
}

/**
 *  The watch projection (UI settings page + facade). Daemon state, never a
 *  second copy of core state.
 */
export type ServiceHostStatus_Serialize = {
  name: string
  version: string
  status: ServiceStatus
  server: StatusResBody_Serialize | null
  phase: ServicePhase
  compat: ServiceCompat
  restart_attempts: number
}

export type ServicePhase =
  | 'probing'
  | 'not_installed'
  | 'daemon_stopped'
  | 'installing'
  | 'starting_daemon'
  | 'ready'
  /**  Version gate failed closed: upgrade required, never downgraded to. */
  | 'incompatible'
  | 'restarting'
  /**  Auto-restart budget spent; waits for `EnsureReady` or a successful explicit start. */
  | 'exhausted'
  | 'uninstalling'
  /**
   *  The probe itself failed or timed out (F5): what the daemon actually
   *  is cannot be determined. Never treated as `DaemonStopped` -- an
   *  unreachable daemon might still be holding a core open, so callers
   *  that gate on "no core held" (the uninstall guard, `RecoverEndpoint`'s
   *  restart) must refuse rather than proceed.
   */
  | 'unknown'

export type ServiceStatus = 'not_installed' | 'stopped' | 'running'

export type ServiceStatusChangedEvent =
  ServiceStatusChangedEvent_Serialize | ServiceStatusChangedEvent_Deserialize

export type ServiceStatusChangedEvent_Deserialize =
  ServiceHostStatus_Deserialize

export type ServiceStatusChangedEvent_Serialize = ServiceHostStatus_Serialize

export type SourceOrigin =
  'scheduled_refresh' | 'manual_refresh' | 'external_file'

export type SourceOutcome =
  | { kind: 'committed'; operation_id: string | null }
  /**  Its result no longer applied to the profile and was dropped (V31). */
  | { kind: 'superseded'; reason: string }
  | { kind: 'failed'; message: string }
  /**
   *  The content reached the source transaction and was refused; nothing
   *  was committed and an external file is never rewritten (V33).
   */
  | { kind: 'rejected'; code: string; message: string }

export type SourceStatus = {
  profile: ProfileId
  name: string
  origin: SourceOrigin
  outcome: SourceOutcome
  health: ConvergenceHealth
  /**  Unix milliseconds. */
  at: number
}

export type SourceVersions = {
  application: number
  clash: number
  session: number
  profiles: number
}

export type StatusResBody = StatusResBody_Serialize | StatusResBody_Deserialize

export type StatusResBody_Deserialize = {
  version: string
  core_infos: CoreInfos_Deserialize
  runtime_infos: RuntimeInfos
  /**
   *  Declared last and omitted rather than null when absent, so a payload
   *  without it is byte-identical to the pre-L3 format — the rule S7 used for
   *  `CoreInfos`. The service always sends it; the `Option` exists so every
   *  existing golden literal stays unchanged.
   */
  logs?: LogPathsInfo_Deserialize | null
  /**  Optional viewer protocol; absence does not affect core control compatibility. */
  log_query_version?: number | null
}

export type StatusResBody_Serialize = {
  version: string
  core_infos: CoreInfos_Serialize
  runtime_infos: RuntimeInfos
  /**
   *  Declared last and omitted rather than null when absent, so a payload
   *  without it is byte-identical to the pre-L3 format — the rule S7 used for
   *  `CoreInfos`. The service always sends it; the `Option` exists so every
   *  existing golden literal stays unchanged.
   */
  logs?: LogPathsInfo_Serialize | null
  /**  Optional viewer protocol; absence does not affect core control compatibility. */
  log_query_version?: number | null
}

export type StepLogEntry = {
  level: StepLogLevel
  message: string
}

/**  1:1 with the legacy `LogSpan` wire shape (enhance/utils.rs:18-25). */
export type StepLogLevel = 'log' | 'info' | 'warn' | 'error'

/**
 *  What a storage operation failed with. Library causes stay in `source`
 *  (skipped on the wire); they reach the user only through the copied detail.
 *  A `key` is the storage key, which the web layer prefixes.
 */
export type StorageOperationError =
  | { kind: 'open_database'; path: string }
  | { kind: 'begin_transaction' }
  | { kind: 'open_table' }
  | { kind: 'read_item'; key: string }
  | { kind: 'write_item'; key: string }
  | { kind: 'remove_item'; key: string }
  | { kind: 'list_items' }
  | { kind: 'commit_transaction' }
  | { kind: 'decode_value'; key: string }
  | { kind: 'encode_value'; key: string }

/**
 *  Event emitted to all windows when a storage value changes.
 *  Event name: `storage-value-changed-event`
 */
export type StorageValueChangedEvent = {
  key: string
  /**  The new JSON-encoded value, or `None` if the key was removed. */
  value: string | null
}

/**
 *  A failure to download a subscription. The URL is not repeated here: the
 *  caller that knows it names it.
 */
export type SubscriptionFetchError =
  | { kind: 'build_http_client' }
  | { kind: 'request_subscription' }
  | { kind: 'subscription_http_status'; status: number }
  | { kind: 'read_subscription_body' }

/**
 *  Identifies one `subscribe_clash_connection_details` call, for a later
 *  `unsubscribe_clash_connection_details`.
 */
export type SubscriptionId = number

/**
 *  Why the system DNS cache could not be flushed. No variant is compiled out
 *  per platform, so the generated bindings do not depend on the build host.
 */
export type SystemDnsError =
  /**
   *  The elevated flush could not be started: the user declined the prompt,
   *  or the platform has no way to ask for elevation.
   */
  | { kind: 'run_flush_command'; command: string }
  /**
   *  The flush ran and reported failure; declining the macOS authorization
   *  dialog lands here too.
   */
  | { kind: 'flush_rejected'; command: string; code: number | null }
  | { kind: 'unsupported' }

export type TrafficRate = {
  download: number
  upload: number
}

export type TransformFailure =
  { kind: 'profile'; id: string } | { kind: 'builtin'; name: string }

export type TransformKind =
  { type: 'overlay' } | { type: 'script'; runtime: ScriptRuntime }

export type TransformOwner =
  { type: 'global' } | { type: 'config'; uid: ProfileId }

/**  Message for inter-window communication */
export type WindowMessageEvent = {
  /**  Source window label */
  from: string
  /**  Target window label (use "*" for broadcast) */
  to: string
  /**  Message type/event name */
  event: string
  /**  Message payload */
  payload: any
}

/**
 *  Event emitted by the frontend when a window's webview is ready and visible.
 *  Carries the window label so the backend can handle per-window logic.
 *  Event name: `window-ready-event`
 */
export type WindowReadyEvent = {
  label: string
}

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}

type EventEmit<T> = [T] extends [null]
  ? () => Promise<void>
  : (payload: T) => Promise<void>

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent =
    (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
      cb({
        ...event,
        payload: deserialize ? deserialize(event.payload) : event.payload,
      })
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload)

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  }

  const fn = (
    target:
      | import('@tauri-apps/api/webview').Webview
      | import('@tauri-apps/api/window').Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) =>
      target.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  })

  return Object.assign(fn, base)
}
