/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMdiTextBoxCheckOutline: typeof import('~icons/mdi/text-box-check-outline.jsx')['default']
}
