[package]
name = 'nyanpasu-helper'
version = '0.1.0'
repository.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap = { version = '4', features = ['derive'] }
serde = { version = '1', features = ['derive'] }
specta = { version = '^2.0.0-rc.25' }
thiserror = '2'
language-tags = '0.3.2'
sys-locale = '0.3.2'
