pub mod clash_api;
mod clash_core;
pub mod handle;
pub mod hotkey;
pub mod logger;
pub mod manager;
pub mod storage;
pub mod sysopt;
pub mod tasks;
pub mod tray;
pub mod updater;
pub mod win_service;
pub mod win_uwp;
pub use self::clash_core::*;
