mod clash;
mod core;
pub mod nyanpasu;
pub mod profile;

pub use self::{
    clash::*,
    core::*,
    profile::{item::*, profiles::*},
};

pub use self::nyanpasu::NyanpasuAppConfig;

/// Prefix for Nyanpasu configs
const NYANPASU_CONFIG_PREFIX: &str = concat!(
    "# Clash Nyanpasu Config. Generated by Nyanpasu v",
    env!("NYANPASU_VERSION")
);
