mod clash;
mod core;
mod draft;
pub mod nyanpasu;
pub mod profile;
mod runtime;
pub use self::{
    clash::*,
    core::*,
    draft::*,
    profile::{item::*, profiles::*},
    runtime::*,
};

pub use self::nyanpasu::NyanpasuAppConfig;

/// Prefix for Nyanpasu configs
const NYANPASU_CONFIG_PREFIX: &str = concat!(
    "# Clash Nyanpasu Config. Generated by Nyanpasu v",
    env!("NYANPASU_VERSION")
);
