declare const classNames: {
  readonly layout: "layout";
  readonly layout__left: "layout__left";
  readonly "the-logo": "the-logo";
  readonly "the-newbtn": "the-newbtn";
  readonly "the-menu": "the-menu";
  readonly "the-traffic": "the-traffic";
  readonly layout__right: "layout__right";
  readonly "the-bar": "the-bar";
  readonly "the-content": "the-content";
  readonly "drag-mask": "drag-mask";
  readonly linux: "linux";
  readonly windows: "windows";
  readonly unknown: "unknown";
  readonly macos: "macos";
  readonly "base-page": "base-page";
  readonly "base-container": "base-container";
  readonly "base-content": "base-content";
  readonly "no-padding": "no-padding";
  readonly "user-none": "user-none";
};
export = classNames;
